// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
)

const adminOverview = `-- name: AdminOverview :one
SELECT
    (SELECT COUNT(*) FROM projects) AS project_count,
    (SELECT COUNT(*) FROM users) AS user_count,
    (SELECT COUNT(*) FROM findings WHERE state IN ('open', 'reopened')) AS open_finding_count,
    (SELECT COUNT(*) FROM reports) AS report_count,
    (SELECT MIN(COALESCE(completed_at, created_at)) FROM reports WHERE status IN ('completed', 'failed')) AS oldest_settled_report_at
`

type AdminOverviewRow struct {
	ProjectCount          int64       `json:"project_count"`
	UserCount             int64       `json:"user_count"`
	OpenFindingCount      int64       `json:"open_finding_count"`
	ReportCount           int64       `json:"report_count"`
	OldestSettledReportAt interface{} `json:"oldest_settled_report_at"`
}

// Platform observability: one row with global counts and the
// oldest settled report, for the admin status surface.
func (q *Queries) AdminOverview(ctx context.Context) (AdminOverviewRow, error) {
	row := q.db.QueryRow(ctx, adminOverview)
	var i AdminOverviewRow
	err := row.Scan(
		&i.ProjectCount,
		&i.UserCount,
		&i.OpenFindingCount,
		&i.ReportCount,
		&i.OldestSettledReportAt,
	)
	return i, err
}
