// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, name, key_prefix, key_hash, last_four, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, key_prefix, key_hash, last_four, scopes, expires_at, last_used_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	KeyPrefix string      `json:"key_prefix"`
	KeyHash   string      `json:"key_hash"`
	LastFour  pgtype.Text `json:"last_four"`
	Scopes    []byte      `json:"scopes"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.LastFour,
		arg.Scopes,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastFour,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id, name, key_prefix, key_hash, last_four, scopes, expires_at, last_used_at, created_at, revoked_at FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastFour,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, name, key_prefix, last_four, scopes, created_at, revoked_at
FROM api_keys
WHERE project_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListAPIKeysByProjectRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	KeyPrefix string             `json:"key_prefix"`
	LastFour  pgtype.Text        `json:"last_four"`
	Scopes    []byte             `json:"scopes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListAPIKeysByProject(ctx context.Context, projectID pgtype.UUID) ([]ListAPIKeysByProjectRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByProjectRow
	for rows.Next() {
		var i ListAPIKeysByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.LastFour,
			&i.Scopes,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked_at = NOW() WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, key_prefix, key_hash, last_four, scopes, expires_at, last_used_at, created_at, revoked_at
`

type RevokeAPIKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastFour,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
