// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteArtifact = `-- name: DeleteArtifact :one
DELETE FROM artifacts
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, target_id, artifact_type, name, version, digest, locator, metadata, created_at
`

type DeleteArtifactParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, deleteArtifact, arg.ID, arg.ProjectID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TargetID,
		&i.ArtifactType,
		&i.Name,
		&i.Version,
		&i.Digest,
		&i.Locator,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, project_id, target_id, artifact_type, name, version, digest, locator, metadata, created_at FROM artifacts
WHERE id = $1 AND project_id = $2
LIMIT 1
`

type GetArtifactParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.ID, arg.ProjectID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TargetID,
		&i.ArtifactType,
		&i.Name,
		&i.Version,
		&i.Digest,
		&i.Locator,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, project_id, target_id, artifact_type, name, version, digest, locator, metadata, created_at FROM artifacts
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) ListArtifacts(ctx context.Context, projectID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetID,
			&i.ArtifactType,
			&i.Name,
			&i.Version,
			&i.Digest,
			&i.Locator,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByTarget = `-- name: ListArtifactsByTarget :many
SELECT id, project_id, target_id, artifact_type, name, version, digest, locator, metadata, created_at FROM artifacts
WHERE target_id = $1
ORDER BY name
`

func (q *Queries) ListArtifactsByTarget(ctx context.Context, targetID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetID,
			&i.ArtifactType,
			&i.Name,
			&i.Version,
			&i.Digest,
			&i.Locator,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifact = `-- name: UpsertArtifact :one
INSERT INTO artifacts (project_id, target_id, artifact_type, name, version, digest, locator, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (project_id, artifact_type, name, digest)
DO UPDATE SET
    target_id = EXCLUDED.target_id,
    version = EXCLUDED.version,
    locator = EXCLUDED.locator,
    metadata = EXCLUDED.metadata
RETURNING id, project_id, target_id, artifact_type, name, version, digest, locator, metadata, created_at
`

type UpsertArtifactParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	TargetID     pgtype.UUID `json:"target_id"`
	ArtifactType string      `json:"artifact_type"`
	Name         string      `json:"name"`
	Version      pgtype.Text `json:"version"`
	Digest       pgtype.Text `json:"digest"`
	Locator      pgtype.Text `json:"locator"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, upsertArtifact,
		arg.ProjectID,
		arg.TargetID,
		arg.ArtifactType,
		arg.Name,
		arg.Version,
		arg.Digest,
		arg.Locator,
		arg.Metadata,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TargetID,
		&i.ArtifactType,
		&i.Name,
		&i.Version,
		&i.Digest,
		&i.Locator,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
