// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEnvironment = `-- name: DeleteEnvironment :one
DELETE FROM environments
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, tier, internet_facing, data_sensitivity, created_at
`

type DeleteEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteEnvironment(ctx context.Context, arg DeleteEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, deleteEnvironment, arg.ID, arg.ProjectID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Tier,
		&i.InternetFacing,
		&i.DataSensitivity,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, project_id, name, tier, internet_facing, data_sensitivity, created_at FROM environments
WHERE id = $1 AND project_id = $2
LIMIT 1
`

type GetEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, arg.ID, arg.ProjectID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Tier,
		&i.InternetFacing,
		&i.DataSensitivity,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, project_id, name, tier, internet_facing, data_sensitivity, created_at FROM environments
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) ListEnvironments(ctx context.Context, projectID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Tier,
			&i.InternetFacing,
			&i.DataSensitivity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironment = `-- name: UpsertEnvironment :one
INSERT INTO environments (project_id, name, tier, internet_facing, data_sensitivity)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, name)
DO UPDATE SET
    tier = EXCLUDED.tier,
    internet_facing = EXCLUDED.internet_facing,
    data_sensitivity = EXCLUDED.data_sensitivity
RETURNING id, project_id, name, tier, internet_facing, data_sensitivity, created_at
`

type UpsertEnvironmentParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	Name            string      `json:"name"`
	Tier            string      `json:"tier"`
	InternetFacing  bool        `json:"internet_facing"`
	DataSensitivity string      `json:"data_sensitivity"`
}

func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(
		ctx, upsertEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Tier,
		arg.InternetFacing,
		arg.DataSensitivity,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Tier,
		&i.InternetFacing,
		&i.DataSensitivity,
		&i.CreatedAt,
	)
	return i, err
}
