// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvidence = `-- name: CreateEvidence :one
INSERT INTO evidence_artifacts (finding_id, type, url, description, uploaded_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, finding_id, type, url, description, uploaded_by, created_at
`

type CreateEvidenceParams struct {
	FindingID   pgtype.UUID `json:"finding_id"`
	Type        string      `json:"type"`
	Url         string      `json:"url"`
	Description string      `json:"description"`
	UploadedBy  pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (EvidenceArtifact, error) {
	row := q.db.QueryRow(ctx, createEvidence,
		arg.FindingID,
		arg.Type,
		arg.Url,
		arg.Description,
		arg.UploadedBy,
	)
	var i EvidenceArtifact
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Type,
		&i.Url,
		&i.Description,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvidence = `-- name: DeleteEvidence :exec
DELETE FROM evidence_artifacts WHERE id = $1
`

func (q *Queries) DeleteEvidence(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvidence, id)
	return err
}

const getEvidenceByID = `-- name: GetEvidenceByID :one
SELECT id, finding_id, type, url, description, uploaded_by, created_at FROM evidence_artifacts WHERE id = $1
`

func (q *Queries) GetEvidenceByID(ctx context.Context, id pgtype.UUID) (EvidenceArtifact, error) {
	row := q.db.QueryRow(ctx, getEvidenceByID, id)
	var i EvidenceArtifact
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Type,
		&i.Url,
		&i.Description,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEvidenceByFinding = `-- name: ListEvidenceByFinding :many
SELECT id, finding_id, type, url, description, uploaded_by, created_at FROM evidence_artifacts
WHERE finding_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListEvidenceByFinding(ctx context.Context, findingID pgtype.UUID) ([]EvidenceArtifact, error) {
	rows, err := q.db.Query(ctx, listEvidenceByFinding, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceArtifact
	for rows.Next() {
		var i EvidenceArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.Type,
			&i.Url,
			&i.Description,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
