// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateFindingEvents = `-- name: BulkCreateFindingEvents :exec
INSERT INTO finding_events (
    finding_id, user_id, event_type, old_value, new_value, comment, changes
)
SELECT
    f_id, $2, $3, $4, $5, $6, $7
FROM UNNEST($1::uuid[]) AS f_id
`

type BulkCreateFindingEventsParams struct {
	Column1   []pgtype.UUID `json:"column_1"`
	UserID    pgtype.UUID   `json:"user_id"`
	EventType string        `json:"event_type"`
	OldValue  pgtype.Text   `json:"old_value"`
	NewValue  pgtype.Text   `json:"new_value"`
	Comment   pgtype.Text   `json:"comment"`
	Changes   []byte        `json:"changes"`
}

func (q *Queries) BulkCreateFindingEvents(ctx context.Context, arg BulkCreateFindingEventsParams) error {
	_, err := q.db.Exec(ctx, bulkCreateFindingEvents,
		arg.Column1,
		arg.UserID,
		arg.EventType,
		arg.OldValue,
		arg.NewValue,
		arg.Comment,
		arg.Changes,
	)
	return err
}

const bulkInsertOccurrences = `-- name: BulkInsertOccurrences :exec
INSERT INTO finding_occurrences (
    finding_id, report_id, title, description,
    severity, severity_rank, score,
    tool_name, tool_version, parser_version,
    location_summary, subject_summary, remediation,
    display, metadata, observed_at
)
SELECT
    f.val::uuid, $1::uuid, t.val::text, d.val::text,
    s.val::text, sr.val::smallint, sc.val::numeric,
    $2::text, $3::text, $4::text,
    loc.val::text, sub.val::text, rem.val::text,
    disp.val::jsonb, meta.val::jsonb, $5::timestamptz
FROM unnest($6::uuid[]) WITH ORDINALITY AS f(val, ord)
JOIN unnest($7::text[]) WITH ORDINALITY AS t(val, ord) ON f.ord = t.ord
JOIN unnest($8::text[]) WITH ORDINALITY AS d(val, ord) ON f.ord = d.ord
JOIN unnest($9::text[]) WITH ORDINALITY AS s(val, ord) ON f.ord = s.ord
JOIN unnest($10::smallint[]) WITH ORDINALITY AS sr(val, ord) ON f.ord = sr.ord
JOIN unnest($11::numeric[]) WITH ORDINALITY AS sc(val, ord) ON f.ord = sc.ord
JOIN unnest($12::text[]) WITH ORDINALITY AS loc(val, ord) ON f.ord = loc.ord
JOIN unnest($13::text[]) WITH ORDINALITY AS sub(val, ord) ON f.ord = sub.ord
JOIN unnest($14::text[]) WITH ORDINALITY AS rem(val, ord) ON f.ord = rem.ord
JOIN unnest($15::jsonb[]) WITH ORDINALITY AS disp(val, ord) ON f.ord = disp.ord
JOIN unnest($16::jsonb[]) WITH ORDINALITY AS meta(val, ord) ON f.ord = meta.ord
ON CONFLICT (finding_id, report_id) DO UPDATE SET observed_at = NOW()
`

type BulkInsertOccurrencesParams struct {
	Column1  pgtype.UUID        `json:"column_1"`
	Column2  string             `json:"column_2"`
	Column3  string             `json:"column_3"`
	Column4  string             `json:"column_4"`
	Column5  pgtype.Timestamptz `json:"column_5"`
	Column6  []pgtype.UUID      `json:"column_6"`
	Column7  []string           `json:"column_7"`
	Column8  []string           `json:"column_8"`
	Column9  []string           `json:"column_9"`
	Column10 []int16            `json:"column_10"`
	Column11 []pgtype.Numeric   `json:"column_11"`
	Column12 []string           `json:"column_12"`
	Column13 []string           `json:"column_13"`
	Column14 []string           `json:"column_14"`
	Column15 [][]byte           `json:"column_15"`
	Column16 [][]byte           `json:"column_16"`
}

func (q *Queries) BulkInsertOccurrences(ctx context.Context, arg BulkInsertOccurrencesParams) error {
	_, err := q.db.Exec(ctx, bulkInsertOccurrences,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
	)
	return err
}

const bulkUpdateFindingAnalysis = `-- name: BulkUpdateFindingAnalysis :many
UPDATE findings SET
    analysis_state = $2,
    gate_effect = $3,
    analysis_expires_at = $4,
    analysis_reason = $5,
    analysis_source = $6,
    manual_override = $7,
    review_required = $8,
    analysis_updated_at = NOW(),
    analysis_updated_by = $9,
    updated_at = NOW()
WHERE id = ANY($1::uuid[])
RETURNING id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha
`

type BulkUpdateFindingAnalysisParams struct {
	Column1           []pgtype.UUID      `json:"column_1"`
	AnalysisState     string             `json:"analysis_state"`
	GateEffect        string             `json:"gate_effect"`
	AnalysisExpiresAt pgtype.Timestamptz `json:"analysis_expires_at"`
	AnalysisReason    pgtype.Text        `json:"analysis_reason"`
	AnalysisSource    string             `json:"analysis_source"`
	ManualOverride    bool               `json:"manual_override"`
	ReviewRequired    bool               `json:"review_required"`
	AnalysisUpdatedBy pgtype.UUID        `json:"analysis_updated_by"`
}

func (q *Queries) BulkUpdateFindingAnalysis(ctx context.Context, arg BulkUpdateFindingAnalysisParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, bulkUpdateFindingAnalysis,
		arg.Column1,
		arg.AnalysisState,
		arg.GateEffect,
		arg.AnalysisExpiresAt,
		arg.AnalysisReason,
		arg.AnalysisSource,
		arg.ManualOverride,
		arg.ReviewRequired,
		arg.AnalysisUpdatedBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverity,
			&i.CurrentSeverityRank,
			&i.CurrentScore,
			&i.State,
			&i.TriageStatus,
			&i.AssigneeID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalysisState,
			&i.GateEffect,
			&i.AnalysisExpiresAt,
			&i.AnalysisReason,
			&i.AnalysisSource,
			&i.AnalysisUpdatedAt,
			&i.AnalysisUpdatedBy,
			&i.ManualOverride,
			&i.ReviewRequired,
			&i.FingerprintVersion,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkUpsertDimensions = `-- name: BulkUpsertDimensions :exec
INSERT INTO finding_dimensions (
    finding_id, dim_key, dim_value, source
)
SELECT
    f.val::uuid, k.val::text, v.val::text, $1::text
FROM unnest($2::uuid[]) WITH ORDINALITY AS f(val, ord)
JOIN unnest($3::text[]) WITH ORDINALITY AS k(val, ord) ON f.ord = k.ord
JOIN unnest($4::text[]) WITH ORDINALITY AS v(val, ord) ON f.ord = v.ord
ON CONFLICT (finding_id, dim_key, dim_value) DO UPDATE SET
    source = EXCLUDED.source
`

type BulkUpsertDimensionsParams struct {
	Column1 string        `json:"column_1"`
	Column2 []pgtype.UUID `json:"column_2"`
	Column3 []string      `json:"column_3"`
	Column4 []string      `json:"column_4"`
}

func (q *Queries) BulkUpsertDimensions(ctx context.Context, arg BulkUpsertDimensionsParams) error {
	_, err := q.db.Exec(ctx, bulkUpsertDimensions,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const bulkUpsertFindings = `-- name: BulkUpsertFindings :many
WITH input_rows AS (
    SELECT
        $1::uuid AS project_id,
        k.val::text AS finding_kind,
        f.val::text AS fingerprint,
        t.val::text AS title,
        s.val::text AS severity,
        sr.val::smallint AS severity_rank,
        sc.val::numeric AS score,
        $2::timestamptz AS observed_at
    FROM unnest($3::text[]) WITH ORDINALITY AS k(val, ord)
    JOIN unnest($4::text[]) WITH ORDINALITY AS f(val, ord) ON k.ord = f.ord
    JOIN unnest($5::text[]) WITH ORDINALITY AS t(val, ord) ON k.ord = t.ord
    JOIN unnest($6::text[]) WITH ORDINALITY AS s(val, ord) ON k.ord = s.ord
    JOIN unnest($7::smallint[]) WITH ORDINALITY AS sr(val, ord) ON k.ord = sr.ord
    JOIN unnest($8::numeric[]) WITH ORDINALITY AS sc(val, ord) ON k.ord = sc.ord
    ORDER BY k.val, f.val
)
INSERT INTO findings (
    project_id, finding_kind, fingerprint,
    current_title, current_severity, current_severity_rank,
    current_score, state, triage_status,
    first_seen_at, last_seen_at
)
SELECT
    ir.project_id, ir.finding_kind, ir.fingerprint,
    ir.title, ir.severity, ir.severity_rank,
    ir.score, 'open', 'untriaged',
    ir.observed_at, ir.observed_at
FROM input_rows ir
ON CONFLICT (project_id, finding_kind, fingerprint) DO UPDATE SET
    current_title = EXCLUDED.current_title,
    current_severity = EXCLUDED.current_severity,
    current_severity_rank = EXCLUDED.current_severity_rank,
    current_score = EXCLUDED.current_score,
    last_seen_at = GREATEST(findings.last_seen_at, EXCLUDED.last_seen_at),
    state = CASE
        WHEN findings.state = 'fixed' THEN 'reopened'
        ELSE findings.state
    END,
    updated_at = NOW()
RETURNING id, fingerprint, (xmax = 0) AS is_inserted, state
`

type BulkUpsertFindingsParams struct {
	Column1 pgtype.UUID        `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 []string           `json:"column_3"`
	Column4 []string           `json:"column_4"`
	Column5 []string           `json:"column_5"`
	Column6 []string           `json:"column_6"`
	Column7 []int16            `json:"column_7"`
	Column8 []pgtype.Numeric   `json:"column_8"`
}

type BulkUpsertFindingsRow struct {
	ID          pgtype.UUID `json:"id"`
	Fingerprint string      `json:"fingerprint"`
	IsInserted  bool        `json:"is_inserted"`
	State       string      `json:"state"`
}

func (q *Queries) BulkUpsertFindings(ctx context.Context, arg BulkUpsertFindingsParams) ([]BulkUpsertFindingsRow, error) {
	rows, err := q.db.Query(ctx, bulkUpsertFindings,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkUpsertFindingsRow
	for rows.Next() {
		var i BulkUpsertFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.IsInserted,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFindingEvent = `-- name: CreateFindingEvent :one
INSERT INTO finding_events (
    finding_id, user_id, event_type, old_value, new_value, comment, changes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, finding_id, user_id, event_type, old_value, new_value, comment, changes, created_at
`

type CreateFindingEventParams struct {
	FindingID pgtype.UUID `json:"finding_id"`
	UserID    pgtype.UUID `json:"user_id"`
	EventType string      `json:"event_type"`
	OldValue  pgtype.Text `json:"old_value"`
	NewValue  pgtype.Text `json:"new_value"`
	Comment   pgtype.Text `json:"comment"`
	Changes   []byte      `json:"changes"`
}

func (q *Queries) CreateFindingEvent(ctx context.Context, arg CreateFindingEventParams) (FindingEvent, error) {
	row := q.db.QueryRow(ctx, createFindingEvent,
		arg.FindingID,
		arg.UserID,
		arg.EventType,
		arg.OldValue,
		arg.NewValue,
		arg.Comment,
		arg.Changes,
	)
	var i FindingEvent
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.UserID,
		&i.EventType,
		&i.OldValue,
		&i.NewValue,
		&i.Comment,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}

const createFindingIfAbsent = `-- name: CreateFindingIfAbsent :one
INSERT INTO findings (
    project_id, finding_kind, fingerprint,
    current_title, current_severity, current_severity_rank,
    current_score, state, triage_status,
    first_seen_at, last_seen_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, 'open', 'untriaged',
    NOW(), NOW()
)
ON CONFLICT (project_id, finding_kind, fingerprint) DO NOTHING
RETURNING id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha
`

type CreateFindingIfAbsentParams struct {
	ProjectID           pgtype.UUID    `json:"project_id"`
	FindingKind         string         `json:"finding_kind"`
	Fingerprint         string         `json:"fingerprint"`
	CurrentTitle        string         `json:"current_title"`
	CurrentSeverity     string         `json:"current_severity"`
	CurrentSeverityRank int16          `json:"current_severity_rank"`
	CurrentScore        pgtype.Numeric `json:"current_score"`
}

// Watcher persist path: insert the finding only when absent. Returns
// pgx.ErrNoRows when a row with the same (project_id, finding_kind,
// fingerprint) already exists — the daemon's re-poll guard. Occurrences are
// created only for genuinely new findings (a new fingerprint), never on
// re-poll hits of an existing watcher finding. The UNIQUE(finding_id,
// report_id) constraint does not dedupe NULL report_ids.
func (q *Queries) CreateFindingIfAbsent(ctx context.Context, arg CreateFindingIfAbsentParams) (Finding, error) {
	row := q.db.QueryRow(ctx, createFindingIfAbsent,
		arg.ProjectID,
		arg.FindingKind,
		arg.Fingerprint,
		arg.CurrentTitle,
		arg.CurrentSeverity,
		arg.CurrentSeverityRank,
		arg.CurrentScore,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisState,
		&i.GateEffect,
		&i.AnalysisExpiresAt,
		&i.AnalysisReason,
		&i.AnalysisSource,
		&i.AnalysisUpdatedAt,
		&i.AnalysisUpdatedBy,
		&i.ManualOverride,
		&i.ReviewRequired,
		&i.FingerprintVersion,
		&i.IntroducedByReportID,
		&i.IntroducedCommitSha,
	)
	return i, err
}

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO finding_occurrences (
    finding_id, report_id, title, description,
    severity, severity_rank, score,
    tool_name, tool_version, parser_version,
    location_summary, subject_summary, remediation,
    display, metadata, observed_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16
) ON CONFLICT (finding_id, report_id) DO UPDATE SET observed_at = NOW()
RETURNING id, finding_id, report_id, title, description, severity, severity_rank, score, tool_name, tool_version, parser_version, location_summary, subject_summary, remediation, display, metadata, observed_at
`

type CreateOccurrenceParams struct {
	FindingID       pgtype.UUID        `json:"finding_id"`
	ReportID        pgtype.UUID        `json:"report_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Severity        string             `json:"severity"`
	SeverityRank    int16              `json:"severity_rank"`
	Score           pgtype.Numeric     `json:"score"`
	ToolName        string             `json:"tool_name"`
	ToolVersion     pgtype.Text        `json:"tool_version"`
	ParserVersion   pgtype.Text        `json:"parser_version"`
	LocationSummary pgtype.Text        `json:"location_summary"`
	SubjectSummary  pgtype.Text        `json:"subject_summary"`
	Remediation     pgtype.Text        `json:"remediation"`
	Display         []byte             `json:"display"`
	Metadata        []byte             `json:"metadata"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (FindingOccurrence, error) {
	row := q.db.QueryRow(ctx, createOccurrence,
		arg.FindingID,
		arg.ReportID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.SeverityRank,
		arg.Score,
		arg.ToolName,
		arg.ToolVersion,
		arg.ParserVersion,
		arg.LocationSummary,
		arg.SubjectSummary,
		arg.Remediation,
		arg.Display,
		arg.Metadata,
		arg.ObservedAt,
	)
	var i FindingOccurrence
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReportID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.SeverityRank,
		&i.Score,
		&i.ToolName,
		&i.ToolVersion,
		&i.ParserVersion,
		&i.LocationSummary,
		&i.SubjectSummary,
		&i.Remediation,
		&i.Display,
		&i.Metadata,
		&i.ObservedAt,
	)
	return i, err
}

const findScaFindingIdForPurlAndCve = `-- name: FindScaFindingIdForPurlAndCve :one
SELECT f.id
FROM findings f
JOIN finding_dimensions dp
  ON dp.finding_id = f.id
 AND dp.dim_key = 'purl'
 AND dp.dim_value != ''
JOIN finding_dimensions dv
  ON dv.finding_id = f.id
 AND dv.dim_key = 'vulnerability_id'
 AND dv.dim_value != ''
WHERE f.project_id = $1
  AND f.finding_kind = 'sca'
  AND COALESCE(substring(dp.dim_value from '^(.*)@'), dp.dim_value) = $2
  AND dv.dim_value = ANY($3::text[])
LIMIT 1
`

type FindScaFindingIdForPurlAndCveParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	PurlName     string      `json:"purl_name"`
	CandidateIds []string    `json:"candidate_ids"`
}

// Gap-fill check for the CVE feed watcher: returns the id of a scan-derived
// SCA finding that already covers the (purl, vulnerability) pair in the
// project, or pgx.ErrNoRows when none does. The watcher must NOT create a
// cve_watcher finding when this returns a row (design: never reopen, never
// duplicate), and it attaches the auto_rule_skipped event to the returned
// finding. The decision conveys the skip but not the suppressing id, so
// the wiring re-uses this query to resolve it.
//
// Matching rules (gap-fill join keys):
//   - purl dimension matches at NAME-LEVEL: the stored dimension value is
//     truncated at the LAST '@' version separator, aligned with the Go
//     purlNameLevel helper (findings.go), so version-less osv-scanner purls
//     still dedupe against versioned watcher candidates. A non-purl fallback
//     containing '@' in its name (e.g. "corp@vendor/pkg@1.0.0") resolves to
//     "corp@vendor/pkg" — the same name-level identity Go computes. Values
//     with no '@' compare verbatim;
//   - vulnerability_id dimension matches ANY candidate id (primary CVE id
//     plus aliases — GHSA-only advisories still dedupe against existing
//     GHSA- or OSV-id findings, never exact-CVE-string only);
//   - findings in ANY state (open or fixed) suppress the watcher — there is
//     no reopen logic.
func (q *Queries) FindScaFindingIdForPurlAndCve(ctx context.Context, arg FindScaFindingIdForPurlAndCveParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findScaFindingIdForPurlAndCve, arg.ProjectID, arg.PurlName, arg.CandidateIds)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getFindingByFingerprint = `-- name: GetFindingByFingerprint :one
SELECT id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha FROM findings
WHERE project_id = $1 AND finding_kind = $2 AND fingerprint = $3
FOR UPDATE
`

type GetFindingByFingerprintParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	FindingKind string      `json:"finding_kind"`
	Fingerprint string      `json:"fingerprint"`
}

func (q *Queries) GetFindingByFingerprint(ctx context.Context, arg GetFindingByFingerprintParams) (Finding, error) {
	row := q.db.QueryRow(ctx, getFindingByFingerprint, arg.ProjectID, arg.FindingKind, arg.Fingerprint)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisState,
		&i.GateEffect,
		&i.AnalysisExpiresAt,
		&i.AnalysisReason,
		&i.AnalysisSource,
		&i.AnalysisUpdatedAt,
		&i.AnalysisUpdatedBy,
		&i.ManualOverride,
		&i.ReviewRequired,
		&i.FingerprintVersion,
		&i.IntroducedByReportID,
		&i.IntroducedCommitSha,
	)
	return i, err
}

const getFindingByID = `-- name: GetFindingByID :one
SELECT id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha FROM findings WHERE id = $1
`

func (q *Queries) GetFindingByID(ctx context.Context, id pgtype.UUID) (Finding, error) {
	row := q.db.QueryRow(ctx, getFindingByID, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisState,
		&i.GateEffect,
		&i.AnalysisExpiresAt,
		&i.AnalysisReason,
		&i.AnalysisSource,
		&i.AnalysisUpdatedAt,
		&i.AnalysisUpdatedBy,
		&i.ManualOverride,
		&i.ReviewRequired,
		&i.FingerprintVersion,
		&i.IntroducedByReportID,
		&i.IntroducedCommitSha,
	)
	return i, err
}

const getFindingContext = `-- name: GetFindingContext :one
SELECT r.environment_id, r.target_id, r.artifact_id
FROM finding_occurrences fo
JOIN reports r ON fo.report_id = r.id
WHERE fo.finding_id = $1
ORDER BY fo.observed_at DESC
LIMIT 1
`

type GetFindingContextRow struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TargetID      pgtype.UUID `json:"target_id"`
	ArtifactID    pgtype.UUID `json:"artifact_id"`
}

func (q *Queries) GetFindingContext(ctx context.Context, findingID pgtype.UUID) (GetFindingContextRow, error) {
	row := q.db.QueryRow(ctx, getFindingContext, findingID)
	var i GetFindingContextRow
	err := row.Scan(&i.EnvironmentID, &i.TargetID, &i.ArtifactID)
	return i, err
}

const getFindingDisplayContext = `-- name: GetFindingDisplayContext :one
SELECT t.name AS target_name, t.kind AS target_kind, t.owner AS target_owner,
    e.name AS environment_name, r.branch AS branch, r.commit_sha AS commit_sha,
    fo.tool_name AS tool_name, fo.location_summary AS location_summary,
    fo.metadata AS metadata
FROM finding_occurrences fo
JOIN reports r ON fo.report_id = r.id
LEFT JOIN targets t ON r.target_id = t.id
LEFT JOIN environments e ON r.environment_id = e.id
WHERE fo.finding_id = $1
ORDER BY fo.observed_at DESC
LIMIT 1
`

type GetFindingDisplayContextRow struct {
	TargetName      pgtype.Text `json:"target_name"`
	TargetKind      pgtype.Text `json:"target_kind"`
	TargetOwner     pgtype.Text `json:"target_owner"`
	EnvironmentName pgtype.Text `json:"environment_name"`
	Branch          pgtype.Text `json:"branch"`
	CommitSha       pgtype.Text `json:"commit_sha"`
	ToolName        string      `json:"tool_name"`
	LocationSummary pgtype.Text `json:"location_summary"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) GetFindingDisplayContext(ctx context.Context, findingID pgtype.UUID) (GetFindingDisplayContextRow, error) {
	row := q.db.QueryRow(ctx, getFindingDisplayContext, findingID)
	var i GetFindingDisplayContextRow
	err := row.Scan(
		&i.TargetName,
		&i.TargetKind,
		&i.TargetOwner,
		&i.EnvironmentName,
		&i.Branch,
		&i.CommitSha,
		&i.ToolName,
		&i.LocationSummary,
		&i.Metadata,
	)
	return i, err
}

const hasDimension = `-- name: HasDimension :one
SELECT EXISTS (
    SELECT 1 FROM finding_dimensions
    WHERE finding_id = $1 AND dim_key = $2 AND dim_value != ''
) AS exists
`

type HasDimensionParams struct {
	FindingID pgtype.UUID `json:"finding_id"`
	DimKey    string      `json:"dim_key"`
}

func (q *Queries) HasDimension(ctx context.Context, arg HasDimensionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasDimension, arg.FindingID, arg.DimKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFindingDimensions = `-- name: ListFindingDimensions :many
SELECT dim_key, dim_value, source
FROM finding_dimensions
WHERE finding_id = $1
ORDER BY dim_key, dim_value
`

type ListFindingDimensionsRow struct {
	DimKey   string      `json:"dim_key"`
	DimValue string      `json:"dim_value"`
	Source   pgtype.Text `json:"source"`
}

func (q *Queries) ListFindingDimensions(ctx context.Context, findingID pgtype.UUID) ([]ListFindingDimensionsRow, error) {
	rows, err := q.db.Query(ctx, listFindingDimensions, findingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingDimensionsRow
	for rows.Next() {
		var i ListFindingDimensionsRow
		if err := rows.Scan(&i.DimKey, &i.DimValue, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingDisplayContextsByIDs = `-- name: ListFindingDisplayContextsByIDs :many
SELECT DISTINCT ON (fo.finding_id)
    fo.finding_id,
    t.name AS target_name, t.kind AS target_kind, t.owner AS target_owner,
    e.name AS environment_name, r.branch AS branch, r.commit_sha AS commit_sha,
    fo.tool_name AS tool_name, fo.location_summary AS location_summary,
    fo.metadata AS metadata
FROM finding_occurrences fo
JOIN reports r ON fo.report_id = r.id
LEFT JOIN targets t ON r.target_id = t.id
LEFT JOIN environments e ON r.environment_id = e.id
WHERE fo.finding_id = ANY($1::uuid[])
ORDER BY fo.finding_id, fo.observed_at DESC
`

type ListFindingDisplayContextsByIDsRow struct {
	FindingID       pgtype.UUID `json:"finding_id"`
	TargetName      pgtype.Text `json:"target_name"`
	TargetKind      pgtype.Text `json:"target_kind"`
	TargetOwner     pgtype.Text `json:"target_owner"`
	EnvironmentName pgtype.Text `json:"environment_name"`
	Branch          pgtype.Text `json:"branch"`
	CommitSha       pgtype.Text `json:"commit_sha"`
	ToolName        string      `json:"tool_name"`
	LocationSummary pgtype.Text `json:"location_summary"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) ListFindingDisplayContextsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListFindingDisplayContextsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listFindingDisplayContextsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFindingDisplayContextsByIDsRow
	for rows.Next() {
		var i ListFindingDisplayContextsByIDsRow
		if err := rows.Scan(
			&i.FindingID,
			&i.TargetName,
			&i.TargetKind,
			&i.TargetOwner,
			&i.EnvironmentName,
			&i.Branch,
			&i.CommitSha,
			&i.ToolName,
			&i.LocationSummary,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingEvents = `-- name: ListFindingEvents :many
SELECT id, finding_id, user_id, event_type, old_value, new_value, comment, changes, created_at FROM finding_events
WHERE finding_id = $1
  AND (array_length($2::text[], 1) IS NULL OR event_type = ANY($2))
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListFindingEventsParams struct {
	FindingID pgtype.UUID `json:"finding_id"`
	Column2   []string    `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListFindingEvents(ctx context.Context, arg ListFindingEventsParams) ([]FindingEvent, error) {
	rows, err := q.db.Query(ctx, listFindingEvents,
		arg.FindingID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindingEvent
	for rows.Next() {
		var i FindingEvent
		if err := rows.Scan(
			&i.ID,
			&i.FindingID,
			&i.UserID,
			&i.EventType,
			&i.OldValue,
			&i.NewValue,
			&i.Comment,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingIDsPresentInReport = `-- name: ListFindingIDsPresentInReport :many
SELECT finding_id FROM finding_occurrences
WHERE report_id = $1
  AND finding_id = ANY($2::uuid[])
`

type ListFindingIDsPresentInReportParams struct {
	ReportID pgtype.UUID   `json:"report_id"`
	Column2  []pgtype.UUID `json:"column_2"`
}

func (q *Queries) ListFindingIDsPresentInReport(ctx context.Context, arg ListFindingIDsPresentInReportParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFindingIDsPresentInReport, arg.ReportID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var finding_id pgtype.UUID
		if err := rows.Scan(&finding_id); err != nil {
			return nil, err
		}
		items = append(items, finding_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByFingerprints = `-- name: ListFindingsByFingerprints :many
SELECT id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha FROM findings
WHERE project_id = $1
  AND finding_kind = $2
  AND fingerprint = ANY($3::text[])
`

type ListFindingsByFingerprintsParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	FindingKind string      `json:"finding_kind"`
	Column3     []string    `json:"column_3"`
}

func (q *Queries) ListFindingsByFingerprints(ctx context.Context, arg ListFindingsByFingerprintsParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByFingerprints, arg.ProjectID, arg.FindingKind, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverity,
			&i.CurrentSeverityRank,
			&i.CurrentScore,
			&i.State,
			&i.TriageStatus,
			&i.AssigneeID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalysisState,
			&i.GateEffect,
			&i.AnalysisExpiresAt,
			&i.AnalysisReason,
			&i.AnalysisSource,
			&i.AnalysisUpdatedAt,
			&i.AnalysisUpdatedBy,
			&i.ManualOverride,
			&i.ReviewRequired,
			&i.FingerprintVersion,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByIDs = `-- name: ListFindingsByIDs :many
SELECT id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha FROM findings WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListFindingsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverity,
			&i.CurrentSeverityRank,
			&i.CurrentScore,
			&i.State,
			&i.TriageStatus,
			&i.AssigneeID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalysisState,
			&i.GateEffect,
			&i.AnalysisExpiresAt,
			&i.AnalysisReason,
			&i.AnalysisSource,
			&i.AnalysisUpdatedAt,
			&i.AnalysisUpdatedBy,
			&i.ManualOverride,
			&i.ReviewRequired,
			&i.FingerprintVersion,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByProject = `-- name: ListFindingsByProject :many
SELECT f.id, f.project_id, f.finding_kind, f.fingerprint, f.current_title, f.current_severity, f.current_severity_rank, f.current_score, f.state, f.triage_status, f.assignee_id, f.first_seen_at, f.last_seen_at, f.fixed_at, f.created_at, f.updated_at, f.analysis_state, f.gate_effect, f.analysis_expires_at, f.analysis_reason, f.analysis_source, f.analysis_updated_at, f.analysis_updated_by, f.manual_override, f.review_required, f.fingerprint_version, f.introduced_by_report_id, f.introduced_commit_sha FROM findings f
WHERE f.project_id = $1
  AND (array_length($2::text[], 1) IS NULL OR f.current_severity = ANY($2))
  AND (array_length($3::text[], 1) IS NULL OR f.state = ANY($3))
  AND (array_length($4::text[], 1) IS NULL OR f.finding_kind = ANY($4))
  AND (array_length($5::text[], 1) IS NULL OR EXISTS (
    SELECT 1 FROM finding_occurrences fo
    JOIN reports r ON fo.report_id = r.id
    JOIN environments e ON r.environment_id = e.id
    WHERE fo.finding_id = f.id AND e.name = ANY($5)))
  AND (array_length($6::text[], 1) IS NULL OR EXISTS (
    SELECT 1 FROM finding_occurrences fo
    JOIN reports r ON fo.report_id = r.id
    JOIN targets t ON r.target_id = t.id
    WHERE fo.finding_id = f.id AND t.name = ANY($6)))
ORDER BY f.current_severity_rank DESC, f.created_at DESC
LIMIT $7 OFFSET $8
`

type ListFindingsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Column2   []string    `json:"column_2"`
	Column3   []string    `json:"column_3"`
	Column4   []string    `json:"column_4"`
	Column5   []string    `json:"column_5"`
	Column6   []string    `json:"column_6"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListFindingsByProject(ctx context.Context, arg ListFindingsByProjectParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByProject,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverity,
			&i.CurrentSeverityRank,
			&i.CurrentScore,
			&i.State,
			&i.TriageStatus,
			&i.AssigneeID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalysisState,
			&i.GateEffect,
			&i.AnalysisExpiresAt,
			&i.AnalysisReason,
			&i.AnalysisSource,
			&i.AnalysisUpdatedAt,
			&i.AnalysisUpdatedBy,
			&i.ManualOverride,
			&i.ReviewRequired,
			&i.FingerprintVersion,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsIntroducedByCommit = `-- name: ListFindingsIntroducedByCommit :many
SELECT id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha FROM findings
WHERE project_id = $1
  AND introduced_commit_sha = $2
ORDER BY current_severity_rank DESC, created_at DESC
`

type ListFindingsIntroducedByCommitParams struct {
	ProjectID           pgtype.UUID `json:"project_id"`
	IntroducedCommitSha pgtype.Text `json:"introduced_commit_sha"`
}

func (q *Queries) ListFindingsIntroducedByCommit(ctx context.Context, arg ListFindingsIntroducedByCommitParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsIntroducedByCommit, arg.ProjectID, arg.IntroducedCommitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverity,
			&i.CurrentSeverityRank,
			&i.CurrentScore,
			&i.State,
			&i.TriageStatus,
			&i.AssigneeID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalysisState,
			&i.GateEffect,
			&i.AnalysisExpiresAt,
			&i.AnalysisReason,
			&i.AnalysisSource,
			&i.AnalysisUpdatedAt,
			&i.AnalysisUpdatedBy,
			&i.ManualOverride,
			&i.ReviewRequired,
			&i.FingerprintVersion,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsIntroducedByReport = `-- name: ListFindingsIntroducedByReport :many
SELECT id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha FROM findings
WHERE project_id = $1 AND introduced_by_report_id = $2
ORDER BY current_severity_rank DESC, created_at DESC
`

type ListFindingsIntroducedByReportParams struct {
	ProjectID            pgtype.UUID `json:"project_id"`
	IntroducedByReportID pgtype.UUID `json:"introduced_by_report_id"`
}

// Findings a single report introduced, for introduced-only gate views and
// change-scoped triage. Pre-existing findings observed (but not introduced)
// by the report are excluded by construction.
func (q *Queries) ListFindingsIntroducedByReport(ctx context.Context, arg ListFindingsIntroducedByReportParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsIntroducedByReport, arg.ProjectID, arg.IntroducedByReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverity,
			&i.CurrentSeverityRank,
			&i.CurrentScore,
			&i.State,
			&i.TriageStatus,
			&i.AssigneeID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FixedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnalysisState,
			&i.GateEffect,
			&i.AnalysisExpiresAt,
			&i.AnalysisReason,
			&i.AnalysisSource,
			&i.AnalysisUpdatedAt,
			&i.AnalysisUpdatedBy,
			&i.ManualOverride,
			&i.ReviewRequired,
			&i.FingerprintVersion,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGateCandidates = `-- name: ListGateCandidates :many
SELECT
    f.id,
    f.project_id,
    f.finding_kind,
    f.fingerprint,
    f.current_title,
    f.current_severity_rank,
    f.analysis_state,
    f.introduced_by_report_id,
    f.introduced_commit_sha,
    COALESCE(ra.state, 'unknown'::reachability_state) AS reachability_state,
    ctx.environment_id,
    ctx.target_id,
    ctx.artifact_id
FROM findings f
LEFT JOIN LATERAL (
    SELECT r.environment_id, r.target_id, r.artifact_id
    FROM finding_occurrences fo
    JOIN reports r ON fo.report_id = r.id
    WHERE fo.finding_id = f.id
    ORDER BY fo.observed_at DESC
    LIMIT 1
) ctx ON true
LEFT JOIN LATERAL (
    SELECT ra.state
    FROM reachability_assessments ra
    WHERE ra.finding_id = f.id
    ORDER BY ra.updated_at DESC
    LIMIT 1
) ra ON true
WHERE f.project_id = $1
  AND f.current_severity_rank >= $2
  AND f.gate_effect = 'block'
  AND f.state IN ('open', 'reopened')
ORDER BY f.current_severity_rank DESC, f.created_at DESC
`

type ListGateCandidatesParams struct {
	ProjectID           pgtype.UUID `json:"project_id"`
	CurrentSeverityRank int16       `json:"current_severity_rank"`
}

type ListGateCandidatesRow struct {
	ID                   pgtype.UUID       `json:"id"`
	ProjectID            pgtype.UUID       `json:"project_id"`
	FindingKind          string            `json:"finding_kind"`
	Fingerprint          string            `json:"fingerprint"`
	CurrentTitle         string            `json:"current_title"`
	CurrentSeverityRank  int16             `json:"current_severity_rank"`
	AnalysisState        string            `json:"analysis_state"`
	IntroducedByReportID pgtype.UUID       `json:"introduced_by_report_id"`
	IntroducedCommitSha  pgtype.Text       `json:"introduced_commit_sha"`
	ReachabilityState    ReachabilityState `json:"reachability_state"`
	EnvironmentID        pgtype.UUID       `json:"environment_id"`
	TargetID             pgtype.UUID       `json:"target_id"`
	ArtifactID           pgtype.UUID       `json:"artifact_id"`
}

// Batch gate-candidate loader: one round trip returns every finding that may
// block a project's gate together with its environment/target/artifact
// context and latest reachability assessment. The query is a performance
// prefilter only — gate.Gate.Evaluate is the authoritative policy. Context
// comes from the most recent occurrence's report; NULL report_id (watcher
// findings) has no context and joins as NULL.
func (q *Queries) ListGateCandidates(ctx context.Context, arg ListGateCandidatesParams) ([]ListGateCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listGateCandidates, arg.ProjectID, arg.CurrentSeverityRank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGateCandidatesRow
	for rows.Next() {
		var i ListGateCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverityRank,
			&i.AnalysisState,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
			&i.ReachabilityState,
			&i.EnvironmentID,
			&i.TargetID,
			&i.ArtifactID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntroducedGateCandidates = `-- name: ListIntroducedGateCandidates :many
SELECT
    f.id,
    f.project_id,
    f.finding_kind,
    f.fingerprint,
    f.current_title,
    f.current_severity_rank,
    f.analysis_state,
    f.introduced_by_report_id,
    f.introduced_commit_sha,
    COALESCE(ra.state, 'unknown'::reachability_state) AS reachability_state,
    ctx.environment_id,
    ctx.target_id,
    ctx.artifact_id,
    rif.change_type
FROM report_introduced_findings rif
JOIN findings f ON rif.finding_id = f.id
LEFT JOIN LATERAL (
    SELECT r.environment_id, r.target_id, r.artifact_id
    FROM finding_occurrences fo
    JOIN reports r ON fo.report_id = r.id
    WHERE fo.finding_id = f.id
    ORDER BY fo.observed_at DESC
    LIMIT 1
) ctx ON true
LEFT JOIN LATERAL (
    SELECT ra.state
    FROM reachability_assessments ra
    WHERE ra.finding_id = f.id
    ORDER BY ra.updated_at DESC
    LIMIT 1
) ra ON true
WHERE rif.report_id = $1
  AND f.current_severity_rank >= $2
  AND f.gate_effect = 'block'
  AND f.state IN ('open', 'reopened')
ORDER BY f.current_severity_rank DESC, f.created_at DESC
`

type ListIntroducedGateCandidatesParams struct {
	ReportID            pgtype.UUID `json:"report_id"`
	CurrentSeverityRank int16       `json:"current_severity_rank"`
}

type ListIntroducedGateCandidatesRow struct {
	ID                   pgtype.UUID       `json:"id"`
	ProjectID            pgtype.UUID       `json:"project_id"`
	FindingKind          string            `json:"finding_kind"`
	Fingerprint          string            `json:"fingerprint"`
	CurrentTitle         string            `json:"current_title"`
	CurrentSeverityRank  int16             `json:"current_severity_rank"`
	AnalysisState        string            `json:"analysis_state"`
	IntroducedByReportID pgtype.UUID       `json:"introduced_by_report_id"`
	IntroducedCommitSha  pgtype.Text       `json:"introduced_commit_sha"`
	ReachabilityState    ReachabilityState `json:"reachability_state"`
	EnvironmentID        pgtype.UUID       `json:"environment_id"`
	TargetID             pgtype.UUID       `json:"target_id"`
	ArtifactID           pgtype.UUID       `json:"artifact_id"`
	ChangeType           string            `json:"change_type"`
}

func (q *Queries) ListIntroducedGateCandidates(ctx context.Context, arg ListIntroducedGateCandidatesParams) ([]ListIntroducedGateCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listIntroducedGateCandidates, arg.ReportID, arg.CurrentSeverityRank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntroducedGateCandidatesRow
	for rows.Next() {
		var i ListIntroducedGateCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FindingKind,
			&i.Fingerprint,
			&i.CurrentTitle,
			&i.CurrentSeverityRank,
			&i.AnalysisState,
			&i.IntroducedByReportID,
			&i.IntroducedCommitSha,
			&i.ReachabilityState,
			&i.EnvironmentID,
			&i.TargetID,
			&i.ArtifactID,
			&i.ChangeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFindingFixed = `-- name: MarkFindingFixed :one
UPDATE findings SET state = 'fixed', updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha
`

func (q *Queries) MarkFindingFixed(ctx context.Context, id pgtype.UUID) (Finding, error) {
	row := q.db.QueryRow(ctx, markFindingFixed, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisState,
		&i.GateEffect,
		&i.AnalysisExpiresAt,
		&i.AnalysisReason,
		&i.AnalysisSource,
		&i.AnalysisUpdatedAt,
		&i.AnalysisUpdatedBy,
		&i.ManualOverride,
		&i.ReviewRequired,
		&i.FingerprintVersion,
		&i.IntroducedByReportID,
		&i.IntroducedCommitSha,
	)
	return i, err
}

const occurrenceExists = `-- name: OccurrenceExists :one
SELECT EXISTS (
    SELECT 1 FROM finding_occurrences
    WHERE finding_id = $1 AND report_id = $2
) AS exists
`

type OccurrenceExistsParams struct {
	FindingID pgtype.UUID `json:"finding_id"`
	ReportID  pgtype.UUID `json:"report_id"`
}

func (q *Queries) OccurrenceExists(ctx context.Context, arg OccurrenceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, occurrenceExists, arg.FindingID, arg.ReportID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordReportIntroducedFindings = `-- name: RecordReportIntroducedFindings :exec
INSERT INTO report_introduced_findings (
    report_id, finding_id, baseline_report_id, change_type
)
SELECT
    $1::uuid, f.val::uuid, $2, ct.val::text
FROM unnest($3::uuid[]) WITH ORDINALITY AS f(val, ord)
JOIN unnest($4::text[]) WITH ORDINALITY AS ct(val, ord) ON f.ord = ct.ord
ON CONFLICT (report_id, finding_id) DO UPDATE SET
    change_type = EXCLUDED.change_type
`

type RecordReportIntroducedFindingsParams struct {
	Column1          pgtype.UUID   `json:"column_1"`
	BaselineReportID pgtype.UUID   `json:"baseline_report_id"`
	Column3          []pgtype.UUID `json:"column_3"`
	Column4          []string      `json:"column_4"`
}

func (q *Queries) RecordReportIntroducedFindings(ctx context.Context, arg RecordReportIntroducedFindingsParams) error {
	_, err := q.db.Exec(ctx, recordReportIntroducedFindings,
		arg.Column1,
		arg.BaselineReportID,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const setFindingIntroducedBy = `-- name: SetFindingIntroducedBy :one
UPDATE findings SET
    introduced_by_report_id = $2,
    introduced_commit_sha = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha
`

type SetFindingIntroducedByParams struct {
	ID                   pgtype.UUID `json:"id"`
	IntroducedByReportID pgtype.UUID `json:"introduced_by_report_id"`
	IntroducedCommitSha  pgtype.Text `json:"introduced_commit_sha"`
}

// Materializes introduced-by-change attribution: the report that
// first observed the finding and the revision it scanned. Set once at
// creation; refreshed only through this query when improved correlation
// evidence arrives, so history stays revisable without silent rewrites.
func (q *Queries) SetFindingIntroducedBy(ctx context.Context, arg SetFindingIntroducedByParams) (Finding, error) {
	row := q.db.QueryRow(ctx, setFindingIntroducedBy, arg.ID, arg.IntroducedByReportID, arg.IntroducedCommitSha)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisState,
		&i.GateEffect,
		&i.AnalysisExpiresAt,
		&i.AnalysisReason,
		&i.AnalysisSource,
		&i.AnalysisUpdatedAt,
		&i.AnalysisUpdatedBy,
		&i.ManualOverride,
		&i.ReviewRequired,
		&i.FingerprintVersion,
		&i.IntroducedByReportID,
		&i.IntroducedCommitSha,
	)
	return i, err
}

const updateFindingAnalysis = `-- name: UpdateFindingAnalysis :one
UPDATE findings SET
    analysis_state = $2,
    gate_effect = $3,
    analysis_expires_at = $4,
    analysis_reason = $5,
    analysis_source = $6,
    manual_override = $7,
    review_required = $8,
    analysis_updated_at = NOW(),
    analysis_updated_by = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha
`

type UpdateFindingAnalysisParams struct {
	ID                pgtype.UUID        `json:"id"`
	AnalysisState     string             `json:"analysis_state"`
	GateEffect        string             `json:"gate_effect"`
	AnalysisExpiresAt pgtype.Timestamptz `json:"analysis_expires_at"`
	AnalysisReason    pgtype.Text        `json:"analysis_reason"`
	AnalysisSource    string             `json:"analysis_source"`
	ManualOverride    bool               `json:"manual_override"`
	ReviewRequired    bool               `json:"review_required"`
	AnalysisUpdatedBy pgtype.UUID        `json:"analysis_updated_by"`
}

func (q *Queries) UpdateFindingAnalysis(ctx context.Context, arg UpdateFindingAnalysisParams) (Finding, error) {
	row := q.db.QueryRow(ctx, updateFindingAnalysis,
		arg.ID,
		arg.AnalysisState,
		arg.GateEffect,
		arg.AnalysisExpiresAt,
		arg.AnalysisReason,
		arg.AnalysisSource,
		arg.ManualOverride,
		arg.ReviewRequired,
		arg.AnalysisUpdatedBy,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisState,
		&i.GateEffect,
		&i.AnalysisExpiresAt,
		&i.AnalysisReason,
		&i.AnalysisSource,
		&i.AnalysisUpdatedAt,
		&i.AnalysisUpdatedBy,
		&i.ManualOverride,
		&i.ReviewRequired,
		&i.FingerprintVersion,
		&i.IntroducedByReportID,
		&i.IntroducedCommitSha,
	)
	return i, err
}

const upsertDimension = `-- name: UpsertDimension :one
INSERT INTO finding_dimensions (
    finding_id, dim_key, dim_value, source
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (finding_id, dim_key, dim_value) DO UPDATE SET
    source = EXCLUDED.source
RETURNING id, finding_id, dim_key, dim_value, source, created_at
`

type UpsertDimensionParams struct {
	FindingID pgtype.UUID `json:"finding_id"`
	DimKey    string      `json:"dim_key"`
	DimValue  string      `json:"dim_value"`
	Source    pgtype.Text `json:"source"`
}

func (q *Queries) UpsertDimension(ctx context.Context, arg UpsertDimensionParams) (FindingDimension, error) {
	row := q.db.QueryRow(ctx, upsertDimension,
		arg.FindingID,
		arg.DimKey,
		arg.DimValue,
		arg.Source,
	)
	var i FindingDimension
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.DimKey,
		&i.DimValue,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFinding = `-- name: UpsertFinding :one
INSERT INTO findings (
    project_id, finding_kind, fingerprint,
    current_title, current_severity, current_severity_rank,
    current_score, state, triage_status,
    first_seen_at, last_seen_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
) ON CONFLICT (project_id, finding_kind, fingerprint) DO UPDATE SET
    current_title = EXCLUDED.current_title,
    current_severity = EXCLUDED.current_severity,
    current_severity_rank = EXCLUDED.current_severity_rank,
    current_score = EXCLUDED.current_score,
    last_seen_at = EXCLUDED.last_seen_at,
    state = CASE
        WHEN findings.state = 'fixed' THEN 'reopened'
        ELSE findings.state
    END,
    updated_at = NOW()
RETURNING id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at, analysis_state, gate_effect, analysis_expires_at, analysis_reason, analysis_source, analysis_updated_at, analysis_updated_by, manual_override, review_required, fingerprint_version, introduced_by_report_id, introduced_commit_sha
`

type UpsertFindingParams struct {
	ProjectID           pgtype.UUID        `json:"project_id"`
	FindingKind         string             `json:"finding_kind"`
	Fingerprint         string             `json:"fingerprint"`
	CurrentTitle        string             `json:"current_title"`
	CurrentSeverity     string             `json:"current_severity"`
	CurrentSeverityRank int16              `json:"current_severity_rank"`
	CurrentScore        pgtype.Numeric     `json:"current_score"`
	State               string             `json:"state"`
	TriageStatus        string             `json:"triage_status"`
	FirstSeenAt         pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, upsertFinding,
		arg.ProjectID,
		arg.FindingKind,
		arg.Fingerprint,
		arg.CurrentTitle,
		arg.CurrentSeverity,
		arg.CurrentSeverityRank,
		arg.CurrentScore,
		arg.State,
		arg.TriageStatus,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnalysisState,
		&i.GateEffect,
		&i.AnalysisExpiresAt,
		&i.AnalysisReason,
		&i.AnalysisSource,
		&i.AnalysisUpdatedAt,
		&i.AnalysisUpdatedBy,
		&i.ManualOverride,
		&i.ReviewRequired,
		&i.FingerprintVersion,
		&i.IntroducedByReportID,
		&i.IntroducedCommitSha,
	)
	return i, err
}
