// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: findings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO finding_occurrences (
    finding_id, report_id, title, description,
    severity, severity_rank, score,
    tool_name, tool_version, parser_version,
    location_summary, subject_summary, remediation,
    display, metadata, observed_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16
) ON CONFLICT (finding_id, report_id) DO NOTHING
RETURNING id, finding_id, report_id, title, description, severity, severity_rank, score, tool_name, tool_version, parser_version, location_summary, subject_summary, remediation, display, metadata, observed_at
`

type CreateOccurrenceParams struct {
	FindingID       pgtype.UUID        `json:"finding_id"`
	ReportID        pgtype.UUID        `json:"report_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Severity        string             `json:"severity"`
	SeverityRank    int16              `json:"severity_rank"`
	Score           pgtype.Numeric     `json:"score"`
	ToolName        string             `json:"tool_name"`
	ToolVersion     pgtype.Text        `json:"tool_version"`
	ParserVersion   pgtype.Text        `json:"parser_version"`
	LocationSummary pgtype.Text        `json:"location_summary"`
	SubjectSummary  pgtype.Text        `json:"subject_summary"`
	Remediation     pgtype.Text        `json:"remediation"`
	Display         []byte             `json:"display"`
	Metadata        []byte             `json:"metadata"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (FindingOccurrence, error) {
	row := q.db.QueryRow(ctx, createOccurrence,
		arg.FindingID,
		arg.ReportID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.SeverityRank,
		arg.Score,
		arg.ToolName,
		arg.ToolVersion,
		arg.ParserVersion,
		arg.LocationSummary,
		arg.SubjectSummary,
		arg.Remediation,
		arg.Display,
		arg.Metadata,
		arg.ObservedAt,
	)
	var i FindingOccurrence
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.ReportID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.SeverityRank,
		&i.Score,
		&i.ToolName,
		&i.ToolVersion,
		&i.ParserVersion,
		&i.LocationSummary,
		&i.SubjectSummary,
		&i.Remediation,
		&i.Display,
		&i.Metadata,
		&i.ObservedAt,
	)
	return i, err
}

const upsertDimension = `-- name: UpsertDimension :one
INSERT INTO finding_dimensions (
    finding_id, dim_key, dim_value, source
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (finding_id, dim_key, dim_value) DO UPDATE SET
    source = EXCLUDED.source
RETURNING id, finding_id, dim_key, dim_value, source, created_at
`

type UpsertDimensionParams struct {
	FindingID pgtype.UUID `json:"finding_id"`
	DimKey    string      `json:"dim_key"`
	DimValue  string      `json:"dim_value"`
	Source    pgtype.Text `json:"source"`
}

func (q *Queries) UpsertDimension(ctx context.Context, arg UpsertDimensionParams) (FindingDimension, error) {
	row := q.db.QueryRow(ctx, upsertDimension,
		arg.FindingID,
		arg.DimKey,
		arg.DimValue,
		arg.Source,
	)
	var i FindingDimension
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.DimKey,
		&i.DimValue,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFinding = `-- name: UpsertFinding :one
INSERT INTO findings (
    project_id, finding_kind, fingerprint,
    current_title, current_severity, current_severity_rank,
    current_score, state, triage_status,
    first_seen_at, last_seen_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
) ON CONFLICT (project_id, finding_kind, fingerprint) DO UPDATE SET
    current_title = EXCLUDED.current_title,
    current_severity = EXCLUDED.current_severity,
    current_severity_rank = EXCLUDED.current_severity_rank,
    current_score = EXCLUDED.current_score,
    last_seen_at = EXCLUDED.last_seen_at,
    state = CASE
        WHEN findings.state = 'fixed' THEN 'reopened'
        ELSE findings.state
    END,
    updated_at = NOW()
RETURNING id, project_id, finding_kind, fingerprint, current_title, current_severity, current_severity_rank, current_score, state, triage_status, assignee_id, first_seen_at, last_seen_at, fixed_at, created_at, updated_at
`

type UpsertFindingParams struct {
	ProjectID           pgtype.UUID        `json:"project_id"`
	FindingKind         string             `json:"finding_kind"`
	Fingerprint         string             `json:"fingerprint"`
	CurrentTitle        string             `json:"current_title"`
	CurrentSeverity     string             `json:"current_severity"`
	CurrentSeverityRank int16              `json:"current_severity_rank"`
	CurrentScore        pgtype.Numeric     `json:"current_score"`
	State               string             `json:"state"`
	TriageStatus        string             `json:"triage_status"`
	FirstSeenAt         pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, upsertFinding,
		arg.ProjectID,
		arg.FindingKind,
		arg.Fingerprint,
		arg.CurrentTitle,
		arg.CurrentSeverity,
		arg.CurrentSeverityRank,
		arg.CurrentScore,
		arg.State,
		arg.TriageStatus,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FindingKind,
		&i.Fingerprint,
		&i.CurrentTitle,
		&i.CurrentSeverity,
		&i.CurrentSeverityRank,
		&i.CurrentScore,
		&i.State,
		&i.TriageStatus,
		&i.AssigneeID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FixedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
