// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (user_id, issuer, subject)
VALUES ($1, $2, $3)
RETURNING id, user_id, issuer, subject, created_at
`

type CreateUserIdentityParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Issuer  string      `json:"issuer"`
	Subject string      `json:"subject"`
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity, arg.UserID, arg.Issuer, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIdentity = `-- name: GetUserIdentity :one
SELECT id, user_id, issuer, subject, created_at FROM user_identities
WHERE issuer = $1 AND subject = $2
`

type GetUserIdentityParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentity, arg.Issuer, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIdentityForUser = `-- name: GetUserIdentityForUser :one
SELECT id, user_id, issuer, subject, created_at FROM user_identities
WHERE user_id = $1 AND issuer = $2
`

type GetUserIdentityForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Issuer string      `json:"issuer"`
}

func (q *Queries) GetUserIdentityForUser(ctx context.Context, arg GetUserIdentityForUserParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityForUser, arg.UserID, arg.Issuer)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}
