// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReportPackages = `-- name: DeleteReportPackages :exec
DELETE FROM report_packages WHERE report_id = $1
`

func (q *Queries) DeleteReportPackages(ctx context.Context, reportID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReportPackages, reportID)
	return err
}

const distinctInventory = `-- name: DistinctInventory :many
SELECT DISTINCT ON (r.project_id, rp.purl)
    r.project_id,
    rp.purl,
    rp.ecosystem,
    rp.name,
    rp.version,
    rp.last_seen_at
FROM report_packages rp
JOIN reports r ON r.id = rp.report_id
WHERE r.project_id = $1
  AND rp.last_seen_at >= NOW() - $2::interval
ORDER BY r.project_id, rp.purl, rp.last_seen_at DESC
`

type DistinctInventoryParams struct {
	ProjectID pgtype.UUID     `json:"project_id"`
	Since     pgtype.Interval `json:"since"`
}

type DistinctInventoryRow struct {
	ProjectID  pgtype.UUID        `json:"project_id"`
	Purl       string             `json:"purl"`
	Ecosystem  pgtype.Text        `json:"ecosystem"`
	Name       pgtype.Text        `json:"name"`
	Version    pgtype.Text        `json:"version"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

// One row per (project_id, purl): duplicate purls across reports collapse, and
// the freshest sighting (last_seen_at DESC) wins the row. ORDER BY must lead
// with the DISTINCT ON expressions per Postgres rules.
func (q *Queries) DistinctInventory(ctx context.Context, arg DistinctInventoryParams) ([]DistinctInventoryRow, error) {
	rows, err := q.db.Query(ctx, distinctInventory, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DistinctInventoryRow
	for rows.Next() {
		var i DistinctInventoryRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Purl,
			&i.Ecosystem,
			&i.Name,
			&i.Version,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReportPackages = `-- name: UpsertReportPackages :exec
INSERT INTO report_packages (
    report_id, purl, ecosystem, name, version, manifest_path
)
SELECT
    $1, package.purl, package.ecosystem,
    package.name, package.version, package.manifest_path
FROM jsonb_to_recordset($2::jsonb) AS package(
    purl text, ecosystem text, name text, version text, manifest_path text
)
WHERE true
ON CONFLICT (report_id, purl) DO UPDATE SET
    last_seen_at = NOW()
`

type UpsertReportPackagesParams struct {
	ReportID pgtype.UUID `json:"report_id"`
	Packages []byte      `json:"packages"`
}

func (q *Queries) UpsertReportPackages(ctx context.Context, arg UpsertReportPackagesParams) error {
	_, err := q.db.Exec(ctx, upsertReportPackages, arg.ReportID, arg.Packages)
	return err
}
