// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireFindings = `-- name: ExpireFindings :many
WITH expired AS (
    SELECT id, project_id, analysis_state, gate_effect
    FROM findings
    WHERE analysis_expires_at IS NOT NULL
      AND analysis_expires_at <= NOW()
    FOR UPDATE
)
UPDATE findings SET
    analysis_state = 'unanalyzed',
    gate_effect = 'block',
    analysis_expires_at = NULL,
    analysis_updated_at = NOW(),
    updated_at = NOW()
FROM expired
WHERE findings.id = expired.id
RETURNING expired.id, expired.project_id, expired.analysis_state, expired.gate_effect
`

type ExpireFindingsRow struct {
	ID            pgtype.UUID `json:"id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	AnalysisState string      `json:"analysis_state"`
	GateEffect    string      `json:"gate_effect"`
}

func (q *Queries) ExpireFindings(ctx context.Context) ([]ExpireFindingsRow, error) {
	rows, err := q.db.Query(ctx, expireFindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireFindingsRow
	for rows.Next() {
		var i ExpireFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AnalysisState,
			&i.GateEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
