// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ReachabilityState string

const (
	ReachabilityStateReachable     ReachabilityState = "reachable"
	ReachabilityStateNotReachable  ReachabilityState = "not_reachable"
	ReachabilityStateUnknown       ReachabilityState = "unknown"
	ReachabilityStateNotApplicable ReachabilityState = "not_applicable"
)

func (e *ReachabilityState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReachabilityState(s)
	case string:
		*e = ReachabilityState(s)
	default:
		return fmt.Errorf("unsupported scan type for ReachabilityState: %T", src)
	}
	return nil
}

type NullReachabilityState struct {
	ReachabilityState ReachabilityState `json:"reachability_state"`
	Valid             bool              `json:"valid"` // Valid is true if ReachabilityState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReachabilityState) Scan(value interface{}) error {
	if value == nil {
		ns.ReachabilityState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReachabilityState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReachabilityState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReachabilityState), nil
}

type SignoffStatus string

const (
	SignoffStatusPending  SignoffStatus = "pending"
	SignoffStatusApproved SignoffStatus = "approved"
	SignoffStatusRejected SignoffStatus = "rejected"
)

func (e *SignoffStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignoffStatus(s)
	case string:
		*e = SignoffStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SignoffStatus: %T", src)
	}
	return nil
}

type NullSignoffStatus struct {
	SignoffStatus SignoffStatus `json:"signoff_status"`
	Valid         bool          `json:"valid"` // Valid is true if SignoffStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignoffStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SignoffStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignoffStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignoffStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignoffStatus), nil
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	LastFour   pgtype.Text        `json:"last_four"`
	Scopes     []byte             `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
}

type Artifact struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	TargetID     pgtype.UUID        `json:"target_id"`
	ArtifactType string             `json:"artifact_type"`
	Name         string             `json:"name"`
	Version      pgtype.Text        `json:"version"`
	Digest       pgtype.Text        `json:"digest"`
	Locator      pgtype.Text        `json:"locator"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Environment struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Name            string             `json:"name"`
	Tier            string             `json:"tier"`
	InternetFacing  bool               `json:"internet_facing"`
	DataSensitivity string             `json:"data_sensitivity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type EvidenceArtifact struct {
	ID          pgtype.UUID        `json:"id"`
	FindingID   pgtype.UUID        `json:"finding_id"`
	Type        string             `json:"type"`
	Url         string             `json:"url"`
	Description string             `json:"description"`
	UploadedBy  pgtype.UUID        `json:"uploaded_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Finding struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	FindingKind          string             `json:"finding_kind"`
	Fingerprint          string             `json:"fingerprint"`
	CurrentTitle         string             `json:"current_title"`
	CurrentSeverity      string             `json:"current_severity"`
	CurrentSeverityRank  int16              `json:"current_severity_rank"`
	CurrentScore         pgtype.Numeric     `json:"current_score"`
	State                string             `json:"state"`
	TriageStatus         string             `json:"triage_status"`
	AssigneeID           pgtype.UUID        `json:"assignee_id"`
	FirstSeenAt          pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	FixedAt              pgtype.Timestamptz `json:"fixed_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	AnalysisState        string             `json:"analysis_state"`
	GateEffect           string             `json:"gate_effect"`
	AnalysisExpiresAt    pgtype.Timestamptz `json:"analysis_expires_at"`
	AnalysisReason       pgtype.Text        `json:"analysis_reason"`
	AnalysisSource       string             `json:"analysis_source"`
	AnalysisUpdatedAt    pgtype.Timestamptz `json:"analysis_updated_at"`
	AnalysisUpdatedBy    pgtype.UUID        `json:"analysis_updated_by"`
	ManualOverride       bool               `json:"manual_override"`
	ReviewRequired       bool               `json:"review_required"`
	FingerprintVersion   int32              `json:"fingerprint_version"`
	IntroducedByReportID pgtype.UUID        `json:"introduced_by_report_id"`
	IntroducedCommitSha  pgtype.Text        `json:"introduced_commit_sha"`
}

type FindingDimension struct {
	ID        pgtype.UUID        `json:"id"`
	FindingID pgtype.UUID        `json:"finding_id"`
	DimKey    string             `json:"dim_key"`
	DimValue  string             `json:"dim_value"`
	Source    pgtype.Text        `json:"source"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FindingEvent struct {
	ID        pgtype.UUID        `json:"id"`
	FindingID pgtype.UUID        `json:"finding_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	EventType string             `json:"event_type"`
	OldValue  pgtype.Text        `json:"old_value"`
	NewValue  pgtype.Text        `json:"new_value"`
	Comment   pgtype.Text        `json:"comment"`
	Changes   []byte             `json:"changes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FindingKind struct {
	Code        string             `json:"code"`
	Label       string             `json:"label"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type FindingOccurrence struct {
	ID              pgtype.UUID        `json:"id"`
	FindingID       pgtype.UUID        `json:"finding_id"`
	ReportID        pgtype.UUID        `json:"report_id"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Severity        string             `json:"severity"`
	SeverityRank    int16              `json:"severity_rank"`
	Score           pgtype.Numeric     `json:"score"`
	ToolName        string             `json:"tool_name"`
	ToolVersion     pgtype.Text        `json:"tool_version"`
	ParserVersion   pgtype.Text        `json:"parser_version"`
	LocationSummary pgtype.Text        `json:"location_summary"`
	SubjectSummary  pgtype.Text        `json:"subject_summary"`
	Remediation     pgtype.Text        `json:"remediation"`
	Display         []byte             `json:"display"`
	Metadata        []byte             `json:"metadata"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
}

type Migration000037UserEmailOriginal struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

type PolicyTemplate struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Definition  []byte             `json:"definition"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID                        pgtype.UUID        `json:"id"`
	Slug                      string             `json:"slug"`
	Name                      string             `json:"name"`
	Description               pgtype.Text        `json:"description"`
	DeploymentThreshold       string             `json:"deployment_threshold"`
	Settings                  []byte             `json:"settings"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	CveWatcherGate            string             `json:"cve_watcher_gate"`
	CveWatcherEnabled         bool               `json:"cve_watcher_enabled"`
	CveWatcherIntervalSeconds int32              `json:"cve_watcher_interval_seconds"`
	PolicyTemplateID          pgtype.UUID        `json:"policy_template_id"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectTeam struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReachabilityAssessment struct {
	ID         pgtype.UUID        `json:"id"`
	FindingID  pgtype.UUID        `json:"finding_id"`
	Evidence   string             `json:"evidence"`
	AssessedBy pgtype.UUID        `json:"assessed_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	State      ReachabilityState  `json:"state"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	ToolName          string             `json:"tool_name"`
	ToolVersion       pgtype.Text        `json:"tool_version"`
	ScanType          string             `json:"scan_type"`
	TargetID          pgtype.UUID        `json:"target_id"`
	ArtifactID        pgtype.UUID        `json:"artifact_id"`
	EnvironmentID     pgtype.UUID        `json:"environment_id"`
	ScanTarget        pgtype.Text        `json:"scan_target"`
	ScanScope         []byte             `json:"scan_scope"`
	ScanScopeHash     pgtype.Text        `json:"scan_scope_hash"`
	ScanCompleteness  string             `json:"scan_completeness"`
	ScannerConfigHash pgtype.Text        `json:"scanner_config_hash"`
	Branch            pgtype.Text        `json:"branch"`
	CommitSha         pgtype.Text        `json:"commit_sha"`
	Status            string             `json:"status"`
	TotalFindings     pgtype.Int4        `json:"total_findings"`
	ParserVersion     pgtype.Text        `json:"parser_version"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	RawReportHash     pgtype.Text        `json:"raw_report_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RawData           []byte             `json:"raw_data"`
	BaseRevision      pgtype.Text        `json:"base_revision"`
	ChangedFiles      []byte             `json:"changed_files"`
	ScanMode          string             `json:"scan_mode"`
}

type ReportIntroducedFinding struct {
	ReportID         pgtype.UUID        `json:"report_id"`
	FindingID        pgtype.UUID        `json:"finding_id"`
	BaselineReportID pgtype.UUID        `json:"baseline_report_id"`
	ChangeType       string             `json:"change_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ReportPackage struct {
	ReportID     pgtype.UUID        `json:"report_id"`
	Purl         string             `json:"purl"`
	Ecosystem    pgtype.Text        `json:"ecosystem"`
	Name         pgtype.Text        `json:"name"`
	Version      pgtype.Text        `json:"version"`
	ManifestPath pgtype.Text        `json:"manifest_path"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
}

type RevokedAccessToken struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Signoff struct {
	ID         pgtype.UUID        `json:"id"`
	FindingID  pgtype.UUID        `json:"finding_id"`
	Status     SignoffStatus      `json:"status"`
	ReviewedBy pgtype.UUID        `json:"reviewed_by"`
	Comment    string             `json:"comment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Target struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	Locator   pgtype.Text        `json:"locator"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Owner     pgtype.Text        `json:"owner"`
}

type Team struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	TeamID    pgtype.UUID        `json:"team_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  pgtype.Text        `json:"display_name"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Waiver struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type WaiverCondition struct {
	ID        pgtype.UUID        `json:"id"`
	WaiverID  pgtype.UUID        `json:"waiver_id"`
	Field     string             `json:"field"`
	Operator  string             `json:"operator"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WaiverContext struct {
	ID            pgtype.UUID        `json:"id"`
	WaiverID      pgtype.UUID        `json:"waiver_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	TargetID      pgtype.UUID        `json:"target_id"`
	ArtifactID    pgtype.UUID        `json:"artifact_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WaiverEvent struct {
	ID        pgtype.UUID        `json:"id"`
	WaiverID  pgtype.UUID        `json:"waiver_id"`
	EventType string             `json:"event_type"`
	ActorID   pgtype.Text        `json:"actor_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WaiverFindingTarget struct {
	ID        pgtype.UUID        `json:"id"`
	WaiverID  pgtype.UUID        `json:"waiver_id"`
	FindingID pgtype.UUID        `json:"finding_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WatcherProjectState struct {
	ProjectID            pgtype.UUID        `json:"project_id"`
	LastSuccessfulPollAt pgtype.Timestamptz `json:"last_successful_poll_at"`
}

type WatcherState struct {
	ID                   int32              `json:"id"`
	LastSuccessfulPollAt pgtype.Timestamptz `json:"last_successful_poll_at"`
	LastPollAttemptAt    pgtype.Timestamptz `json:"last_poll_attempt_at"`
	LastError            pgtype.Text        `json:"last_error"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
}
