// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPolicyTemplate = `-- name: CreatePolicyTemplate :one
INSERT INTO policy_templates (name, description, definition)
VALUES ($1, $2, $3)
RETURNING id, name, description, definition, version, created_at, updated_at
`

type CreatePolicyTemplateParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Definition  []byte `json:"definition"`
}

func (q *Queries) CreatePolicyTemplate(ctx context.Context, arg CreatePolicyTemplateParams) (PolicyTemplate, error) {
	row := q.db.QueryRow(ctx, createPolicyTemplate, arg.Name, arg.Description, arg.Definition)
	var i PolicyTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePolicyTemplate = `-- name: DeletePolicyTemplate :exec
DELETE FROM policy_templates WHERE id = $1
`

func (q *Queries) DeletePolicyTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicyTemplate, id)
	return err
}

const getPolicyTemplateByID = `-- name: GetPolicyTemplateByID :one
SELECT id, name, description, definition, version, created_at, updated_at FROM policy_templates WHERE id = $1
`

func (q *Queries) GetPolicyTemplateByID(ctx context.Context, id pgtype.UUID) (PolicyTemplate, error) {
	row := q.db.QueryRow(ctx, getPolicyTemplateByID, id)
	var i PolicyTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyTemplateByName = `-- name: GetPolicyTemplateByName :one
SELECT id, name, description, definition, version, created_at, updated_at FROM policy_templates WHERE name = $1
`

func (q *Queries) GetPolicyTemplateByName(ctx context.Context, name string) (PolicyTemplate, error) {
	row := q.db.QueryRow(ctx, getPolicyTemplateByName, name)
	var i PolicyTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPolicyTemplates = `-- name: ListPolicyTemplates :many
SELECT id, name, description, definition, version, created_at, updated_at FROM policy_templates
ORDER BY name ASC
`

func (q *Queries) ListPolicyTemplates(ctx context.Context) ([]PolicyTemplate, error) {
	rows, err := q.db.Query(ctx, listPolicyTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyTemplate
	for rows.Next() {
		var i PolicyTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectPolicyTemplate = `-- name: SetProjectPolicyTemplate :one
UPDATE projects SET
    policy_template_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, description, deployment_threshold, settings, created_at, updated_at, cve_watcher_gate, cve_watcher_enabled, cve_watcher_interval_seconds, policy_template_id
`

type SetProjectPolicyTemplateParams struct {
	ID               pgtype.UUID `json:"id"`
	PolicyTemplateID pgtype.UUID `json:"policy_template_id"`
}

func (q *Queries) SetProjectPolicyTemplate(ctx context.Context, arg SetProjectPolicyTemplateParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectPolicyTemplate, arg.ID, arg.PolicyTemplateID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DeploymentThreshold,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CveWatcherGate,
		&i.CveWatcherEnabled,
		&i.CveWatcherIntervalSeconds,
		&i.PolicyTemplateID,
	)
	return i, err
}

const updatePolicyTemplate = `-- name: UpdatePolicyTemplate :one
UPDATE policy_templates SET
    name = $2,
    description = $3,
    definition = $4,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, definition, version, created_at, updated_at
`

type UpdatePolicyTemplateParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Definition  []byte      `json:"definition"`
}

// Definition replacement bumps the version so consumers can tell a
// baseline moved underneath them; name changes ride the same row.
func (q *Queries) UpdatePolicyTemplate(ctx context.Context, arg UpdatePolicyTemplateParams) (PolicyTemplate, error) {
	row := q.db.QueryRow(ctx, updatePolicyTemplate,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Definition,
	)
	var i PolicyTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
