// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    project_id, tool_name, tool_version, scan_type,
    target_id, artifact_id, environment_id,
    scan_target, scan_scope, scan_scope_hash,
    scan_completeness, scanner_config_hash,
    branch, commit_sha, status,
    total_findings, parser_version,
    started_at, error_message, raw_report_hash
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14, $15,
    $16, $17,
    $18, $19, $20
) RETURNING id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at
`

type CreateReportParams struct {
	ProjectID         pgtype.UUID        `json:"project_id"`
	ToolName          string             `json:"tool_name"`
	ToolVersion       pgtype.Text        `json:"tool_version"`
	ScanType          string             `json:"scan_type"`
	TargetID          pgtype.UUID        `json:"target_id"`
	ArtifactID        pgtype.UUID        `json:"artifact_id"`
	EnvironmentID     pgtype.UUID        `json:"environment_id"`
	ScanTarget        pgtype.Text        `json:"scan_target"`
	ScanScope         []byte             `json:"scan_scope"`
	ScanScopeHash     pgtype.Text        `json:"scan_scope_hash"`
	ScanCompleteness  string             `json:"scan_completeness"`
	ScannerConfigHash pgtype.Text        `json:"scanner_config_hash"`
	Branch            pgtype.Text        `json:"branch"`
	CommitSha         pgtype.Text        `json:"commit_sha"`
	Status            string             `json:"status"`
	TotalFindings     pgtype.Int4        `json:"total_findings"`
	ParserVersion     pgtype.Text        `json:"parser_version"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	RawReportHash     pgtype.Text        `json:"raw_report_hash"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ProjectID,
		arg.ToolName,
		arg.ToolVersion,
		arg.ScanType,
		arg.TargetID,
		arg.ArtifactID,
		arg.EnvironmentID,
		arg.ScanTarget,
		arg.ScanScope,
		arg.ScanScopeHash,
		arg.ScanCompleteness,
		arg.ScannerConfigHash,
		arg.Branch,
		arg.CommitSha,
		arg.Status,
		arg.TotalFindings,
		arg.ParserVersion,
		arg.StartedAt,
		arg.ErrorMessage,
		arg.RawReportHash,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.TargetID,
		&i.ArtifactID,
		&i.EnvironmentID,
		&i.ScanTarget,
		&i.ScanScope,
		&i.ScanScopeHash,
		&i.ScanCompleteness,
		&i.ScannerConfigHash,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.TotalFindings,
		&i.ParserVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.RawReportHash,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.TargetID,
		&i.ArtifactID,
		&i.EnvironmentID,
		&i.ScanTarget,
		&i.ScanScope,
		&i.ScanScopeHash,
		&i.ScanCompleteness,
		&i.ScannerConfigHash,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.TotalFindings,
		&i.ParserVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.RawReportHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports SET
    status = $2,
    total_findings = $3,
    completed_at = CASE WHEN $2 = 'completed' OR $2 = 'failed' THEN NOW() ELSE completed_at END,
    error_message = $4
WHERE id = $1 AND project_id = $5
RETURNING id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at
`

type UpdateReportStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	TotalFindings pgtype.Int4 `json:"total_findings"`
	ErrorMessage  pgtype.Text `json:"error_message"`
	ProjectID     pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus,
		arg.ID,
		arg.Status,
		arg.TotalFindings,
		arg.ErrorMessage,
		arg.ProjectID,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.TargetID,
		&i.ArtifactID,
		&i.EnvironmentID,
		&i.ScanTarget,
		&i.ScanScope,
		&i.ScanScopeHash,
		&i.ScanCompleteness,
		&i.ScannerConfigHash,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.TotalFindings,
		&i.ParserVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.RawReportHash,
		&i.CreatedAt,
	)
	return i, err
}
