// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    project_id, tool_name, tool_version, scan_type,
    target_id, artifact_id, environment_id,
    scan_target, scan_scope, scan_scope_hash,
    scan_completeness, scanner_config_hash,
    branch, commit_sha, status,
    total_findings, parser_version,
    started_at, error_message, raw_report_hash,
    raw_data,
    base_revision, changed_files, scan_mode
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14, $15,
    $16, $17,
    $18, $19, $20,
    $21,
    $22, $23, $24
) RETURNING id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at, raw_data, base_revision, changed_files, scan_mode
`

type CreateReportParams struct {
	ProjectID         pgtype.UUID        `json:"project_id"`
	ToolName          string             `json:"tool_name"`
	ToolVersion       pgtype.Text        `json:"tool_version"`
	ScanType          string             `json:"scan_type"`
	TargetID          pgtype.UUID        `json:"target_id"`
	ArtifactID        pgtype.UUID        `json:"artifact_id"`
	EnvironmentID     pgtype.UUID        `json:"environment_id"`
	ScanTarget        pgtype.Text        `json:"scan_target"`
	ScanScope         []byte             `json:"scan_scope"`
	ScanScopeHash     pgtype.Text        `json:"scan_scope_hash"`
	ScanCompleteness  string             `json:"scan_completeness"`
	ScannerConfigHash pgtype.Text        `json:"scanner_config_hash"`
	Branch            pgtype.Text        `json:"branch"`
	CommitSha         pgtype.Text        `json:"commit_sha"`
	Status            string             `json:"status"`
	TotalFindings     pgtype.Int4        `json:"total_findings"`
	ParserVersion     pgtype.Text        `json:"parser_version"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	RawReportHash     pgtype.Text        `json:"raw_report_hash"`
	RawData           []byte             `json:"raw_data"`
	BaseRevision      pgtype.Text        `json:"base_revision"`
	ChangedFiles      []byte             `json:"changed_files"`
	ScanMode          string             `json:"scan_mode"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ProjectID,
		arg.ToolName,
		arg.ToolVersion,
		arg.ScanType,
		arg.TargetID,
		arg.ArtifactID,
		arg.EnvironmentID,
		arg.ScanTarget,
		arg.ScanScope,
		arg.ScanScopeHash,
		arg.ScanCompleteness,
		arg.ScannerConfigHash,
		arg.Branch,
		arg.CommitSha,
		arg.Status,
		arg.TotalFindings,
		arg.ParserVersion,
		arg.StartedAt,
		arg.ErrorMessage,
		arg.RawReportHash,
		arg.RawData,
		arg.BaseRevision,
		arg.ChangedFiles,
		arg.ScanMode,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.TargetID,
		&i.ArtifactID,
		&i.EnvironmentID,
		&i.ScanTarget,
		&i.ScanScope,
		&i.ScanScopeHash,
		&i.ScanCompleteness,
		&i.ScannerConfigHash,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.TotalFindings,
		&i.ParserVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.RawReportHash,
		&i.CreatedAt,
		&i.RawData,
		&i.BaseRevision,
		&i.ChangedFiles,
		&i.ScanMode,
	)
	return i, err
}

const getCompletedReportByCommit = `-- name: GetCompletedReportByCommit :one
SELECT id, tool_name, branch, commit_sha, base_revision, scan_mode, scan_completeness, created_at
FROM reports
WHERE project_id = $1 AND tool_name = $2 AND commit_sha = $3 AND status = 'completed' AND scan_mode = 'full'
ORDER BY created_at DESC
LIMIT 1
`

type GetCompletedReportByCommitParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ToolName  string      `json:"tool_name"`
	CommitSha pgtype.Text `json:"commit_sha"`
}

type GetCompletedReportByCommitRow struct {
	ID               pgtype.UUID        `json:"id"`
	ToolName         string             `json:"tool_name"`
	Branch           pgtype.Text        `json:"branch"`
	CommitSha        pgtype.Text        `json:"commit_sha"`
	BaseRevision     pgtype.Text        `json:"base_revision"`
	ScanMode         string             `json:"scan_mode"`
	ScanCompleteness string             `json:"scan_completeness"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Baseline resolution for incremental analysis (SOLO-165): the newest
// completed same-scanner report for an exact revision. pgx.ErrNoRows means
// no baseline exists for the base revision — the caller falls back to a
// full scan instead of guessing.
func (q *Queries) GetCompletedReportByCommit(ctx context.Context, arg GetCompletedReportByCommitParams) (GetCompletedReportByCommitRow, error) {
	row := q.db.QueryRow(ctx, getCompletedReportByCommit, arg.ProjectID, arg.ToolName, arg.CommitSha)
	var i GetCompletedReportByCommitRow
	err := row.Scan(
		&i.ID,
		&i.ToolName,
		&i.Branch,
		&i.CommitSha,
		&i.BaseRevision,
		&i.ScanMode,
		&i.ScanCompleteness,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at, raw_data, base_revision, changed_files, scan_mode FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.TargetID,
		&i.ArtifactID,
		&i.EnvironmentID,
		&i.ScanTarget,
		&i.ScanScope,
		&i.ScanScopeHash,
		&i.ScanCompleteness,
		&i.ScannerConfigHash,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.TotalFindings,
		&i.ParserVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.RawReportHash,
		&i.CreatedAt,
		&i.RawData,
		&i.BaseRevision,
		&i.ChangedFiles,
		&i.ScanMode,
	)
	return i, err
}

const latestCompletedReportByScanner = `-- name: LatestCompletedReportByScanner :one
SELECT id, tool_name, branch, commit_sha, scan_completeness, created_at
FROM reports
WHERE project_id = $1 AND tool_name = $2 AND status = 'completed' AND scan_mode = 'full'
ORDER BY created_at DESC
LIMIT 1
`

type LatestCompletedReportByScannerParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	ToolName  string      `json:"tool_name"`
}

type LatestCompletedReportByScannerRow struct {
	ID               pgtype.UUID        `json:"id"`
	ToolName         string             `json:"tool_name"`
	Branch           pgtype.Text        `json:"branch"`
	CommitSha        pgtype.Text        `json:"commit_sha"`
	ScanCompleteness string             `json:"scan_completeness"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LatestCompletedReportByScanner(ctx context.Context, arg LatestCompletedReportByScannerParams) (LatestCompletedReportByScannerRow, error) {
	row := q.db.QueryRow(ctx, latestCompletedReportByScanner, arg.ProjectID, arg.ToolName)
	var i LatestCompletedReportByScannerRow
	err := row.Scan(
		&i.ID,
		&i.ToolName,
		&i.Branch,
		&i.CommitSha,
		&i.ScanCompleteness,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsByProject = `-- name: ListReportsByProject :many
SELECT id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at, raw_data, base_revision, changed_files, scan_mode FROM reports
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReportsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListReportsByProject(ctx context.Context, arg ListReportsByProjectParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ToolName,
			&i.ToolVersion,
			&i.ScanType,
			&i.TargetID,
			&i.ArtifactID,
			&i.EnvironmentID,
			&i.ScanTarget,
			&i.ScanScope,
			&i.ScanScopeHash,
			&i.ScanCompleteness,
			&i.ScannerConfigHash,
			&i.Branch,
			&i.CommitSha,
			&i.Status,
			&i.TotalFindings,
			&i.ParserVersion,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.RawReportHash,
			&i.CreatedAt,
			&i.RawData,
			&i.BaseRevision,
			&i.ChangedFiles,
			&i.ScanMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports SET
    status = $2,
    total_findings = $3,
    completed_at = CASE WHEN $2 = 'completed' OR $2 = 'failed' THEN NOW() ELSE completed_at END,
    error_message = $4
WHERE id = $1 AND project_id = $5
RETURNING id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at, raw_data, base_revision, changed_files, scan_mode
`

type UpdateReportStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	TotalFindings pgtype.Int4 `json:"total_findings"`
	ErrorMessage  pgtype.Text `json:"error_message"`
	ProjectID     pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus,
		arg.ID,
		arg.Status,
		arg.TotalFindings,
		arg.ErrorMessage,
		arg.ProjectID,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.TargetID,
		&i.ArtifactID,
		&i.EnvironmentID,
		&i.ScanTarget,
		&i.ScanScope,
		&i.ScanScopeHash,
		&i.ScanCompleteness,
		&i.ScannerConfigHash,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.TotalFindings,
		&i.ParserVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.RawReportHash,
		&i.CreatedAt,
		&i.RawData,
		&i.BaseRevision,
		&i.ChangedFiles,
		&i.ScanMode,
	)
	return i, err
}
