// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocation.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isAccessTokenRevoked = `-- name: IsAccessTokenRevoked :one
SELECT EXISTS (
    SELECT 1 FROM revoked_access_tokens
    WHERE jti = $1 AND expires_at > NOW()
) AS revoked
`

func (q *Queries) IsAccessTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccessTokenRevoked, jti)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const pruneRevokedAccessTokens = `-- name: PruneRevokedAccessTokens :exec
DELETE FROM revoked_access_tokens
WHERE ctid IN (
    SELECT ctid FROM revoked_access_tokens
    WHERE expires_at <= NOW()
    LIMIT 1000
)
`

func (q *Queries) PruneRevokedAccessTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneRevokedAccessTokens)
	return err
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
INSERT INTO revoked_access_tokens (jti, expires_at)
VALUES ($1, $2)
ON CONFLICT (jti) DO UPDATE SET expires_at = EXCLUDED.expires_at
`

type RevokeAccessTokenParams struct {
	Jti       string             `json:"jti"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, arg.Jti, arg.ExpiresAt)
	return err
}
