// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signoffs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSignoffByFinding = `-- name: GetSignoffByFinding :one
SELECT id, finding_id, status, reviewed_by, comment, created_at, updated_at FROM signoffs WHERE finding_id = $1
`

func (q *Queries) GetSignoffByFinding(ctx context.Context, findingID pgtype.UUID) (Signoff, error) {
	row := q.db.QueryRow(ctx, getSignoffByFinding, findingID)
	var i Signoff
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Status,
		&i.ReviewedBy,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSignoff = `-- name: UpsertSignoff :one
INSERT INTO signoffs (finding_id, status, reviewed_by, comment)
VALUES ($1, $2, $3, $4)
ON CONFLICT (finding_id) DO UPDATE SET
    status = EXCLUDED.status,
    reviewed_by = EXCLUDED.reviewed_by,
    comment = EXCLUDED.comment,
    updated_at = now()
RETURNING id, finding_id, status, reviewed_by, comment, created_at, updated_at
`

type UpsertSignoffParams struct {
	FindingID  pgtype.UUID   `json:"finding_id"`
	Status     SignoffStatus `json:"status"`
	ReviewedBy pgtype.UUID   `json:"reviewed_by"`
	Comment    string        `json:"comment"`
}

func (q *Queries) UpsertSignoff(ctx context.Context, arg UpsertSignoffParams) (Signoff, error) {
	row := q.db.QueryRow(ctx, upsertSignoff,
		arg.FindingID,
		arg.Status,
		arg.ReviewedBy,
		arg.Comment,
	)
	var i Signoff
	err := row.Scan(
		&i.ID,
		&i.FindingID,
		&i.Status,
		&i.ReviewedBy,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
