// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectLatestReport = `-- name: GetProjectLatestReport :one
SELECT id, project_id, tool_name, tool_version, scan_type, target_id, artifact_id, environment_id, scan_target, scan_scope, scan_scope_hash, scan_completeness, scanner_config_hash, branch, commit_sha, status, total_findings, parser_version, started_at, completed_at, error_message, raw_report_hash, created_at, raw_data
FROM reports
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetProjectLatestReport(ctx context.Context, projectID pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getProjectLatestReport, projectID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.TargetID,
		&i.ArtifactID,
		&i.EnvironmentID,
		&i.ScanTarget,
		&i.ScanScope,
		&i.ScanScopeHash,
		&i.ScanCompleteness,
		&i.ScannerConfigHash,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.TotalFindings,
		&i.ParserVersion,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.RawReportHash,
		&i.CreatedAt,
		&i.RawData,
	)
	return i, err
}

const getProjectReportCount = `-- name: GetProjectReportCount :one
SELECT COUNT(*)::int AS count
FROM reports
WHERE project_id = $1
`

func (q *Queries) GetProjectReportCount(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getProjectReportCount, projectID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getProjectStats = `-- name: GetProjectStats :many
SELECT
    f.current_severity AS severity,
    COUNT(*)::int AS count,
    COUNT(*) FILTER (WHERE f.gate_effect = 'block')::int AS blocking_count
FROM findings f
WHERE f.project_id = $1
GROUP BY f.current_severity
ORDER BY MIN(f.current_severity_rank)
`

type GetProjectStatsRow struct {
	Severity      string `json:"severity"`
	Count         int32  `json:"count"`
	BlockingCount int32  `json:"blocking_count"`
}

func (q *Queries) GetProjectStats(ctx context.Context, projectID pgtype.UUID) ([]GetProjectStatsRow, error) {
	rows, err := q.db.Query(ctx, getProjectStats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectStatsRow
	for rows.Next() {
		var i GetProjectStatsRow
		if err := rows.Scan(&i.Severity, &i.Count, &i.BlockingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectWaiverCount = `-- name: GetProjectWaiverCount :one
SELECT COUNT(*)::int AS count
FROM waivers
WHERE project_id = $1 AND enabled = true
`

func (q *Queries) GetProjectWaiverCount(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getProjectWaiverCount, projectID)
	var count int32
	err := row.Scan(&count)
	return count, err
}
