// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgingRows = `-- name: GetAgingRows :many
SELECT
    f.id,
    f.current_title,
    f.current_severity,
    f.current_severity_rank,
    f.first_seen_at,
    f.state,
    EXISTS (
        SELECT 1 FROM finding_events e
        WHERE e.finding_id = f.id AND e.event_type LIKE 'reopened%'
    ) AS reopened
FROM findings f
WHERE f.project_id = $1
ORDER BY f.first_seen_at ASC, f.id ASC
LIMIT 10000
`

type GetAgingRowsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	CurrentTitle        string             `json:"current_title"`
	CurrentSeverity     string             `json:"current_severity"`
	CurrentSeverityRank int16              `json:"current_severity_rank"`
	FirstSeenAt         pgtype.Timestamptz `json:"first_seen_at"`
	State               string             `json:"state"`
	Reopened            bool               `json:"reopened"`
}

func (q *Queries) GetAgingRows(ctx context.Context, projectID pgtype.UUID) ([]GetAgingRowsRow, error) {
	rows, err := q.db.Query(ctx, getAgingRows, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgingRowsRow
	for rows.Next() {
		var i GetAgingRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.CurrentTitle,
			&i.CurrentSeverity,
			&i.CurrentSeverityRank,
			&i.FirstSeenAt,
			&i.State,
			&i.Reopened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectAnalysisStateCounts = `-- name: GetProjectAnalysisStateCounts :many
SELECT
    COALESCE(NULLIF(f.analysis_state, ''), 'unanalyzed')::text AS state,
    COUNT(*)::int AS count
FROM findings f
WHERE f.project_id = $1
GROUP BY COALESCE(NULLIF(f.analysis_state, ''), 'unanalyzed')
ORDER BY state ASC
`

type GetProjectAnalysisStateCountsRow struct {
	State string `json:"state"`
	Count int32  `json:"count"`
}

func (q *Queries) GetProjectAnalysisStateCounts(ctx context.Context, projectID pgtype.UUID) ([]GetProjectAnalysisStateCountsRow, error) {
	rows, err := q.db.Query(ctx, getProjectAnalysisStateCounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectAnalysisStateCountsRow
	for rows.Next() {
		var i GetProjectAnalysisStateCountsRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectLatestReport = `-- name: GetProjectLatestReport :one
SELECT
    id, project_id, tool_name, tool_version, scan_type,
    scan_target, status, total_findings, branch, commit_sha,
    created_at, completed_at
FROM reports
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetProjectLatestReportRow struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ToolName      string             `json:"tool_name"`
	ToolVersion   pgtype.Text        `json:"tool_version"`
	ScanType      string             `json:"scan_type"`
	ScanTarget    pgtype.Text        `json:"scan_target"`
	Status        string             `json:"status"`
	TotalFindings pgtype.Int4        `json:"total_findings"`
	Branch        pgtype.Text        `json:"branch"`
	CommitSha     pgtype.Text        `json:"commit_sha"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetProjectLatestReport(ctx context.Context, projectID pgtype.UUID) (GetProjectLatestReportRow, error) {
	row := q.db.QueryRow(ctx, getProjectLatestReport, projectID)
	var i GetProjectLatestReportRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ToolName,
		&i.ToolVersion,
		&i.ScanType,
		&i.ScanTarget,
		&i.Status,
		&i.TotalFindings,
		&i.Branch,
		&i.CommitSha,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProjectReportCount = `-- name: GetProjectReportCount :one
SELECT COUNT(*)::int AS count
FROM reports
WHERE project_id = $1
`

func (q *Queries) GetProjectReportCount(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getProjectReportCount, projectID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getProjectStats = `-- name: GetProjectStats :many
SELECT
    f.current_severity AS severity,
    COUNT(*)::int AS count,
    COUNT(*) FILTER (WHERE f.gate_effect = 'block')::int AS blocking_count
FROM findings f
WHERE f.project_id = $1
GROUP BY f.current_severity
ORDER BY MIN(f.current_severity_rank)
`

type GetProjectStatsRow struct {
	Severity      string `json:"severity"`
	Count         int32  `json:"count"`
	BlockingCount int32  `json:"blocking_count"`
}

func (q *Queries) GetProjectStats(ctx context.Context, projectID pgtype.UUID) ([]GetProjectStatsRow, error) {
	rows, err := q.db.Query(ctx, getProjectStats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectStatsRow
	for rows.Next() {
		var i GetProjectStatsRow
		if err := rows.Scan(&i.Severity, &i.Count, &i.BlockingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectWaiverCount = `-- name: GetProjectWaiverCount :one
SELECT COUNT(*)::int AS count
FROM waivers
WHERE project_id = $1 AND enabled = true
`

func (q *Queries) GetProjectWaiverCount(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getProjectWaiverCount, projectID)
	var count int32
	err := row.Scan(&count)
	return count, err
}
