// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: targets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTarget = `-- name: DeleteTarget :one
DELETE FROM targets
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, kind, locator, created_at
`

type DeleteTargetParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteTarget(ctx context.Context, arg DeleteTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, deleteTarget, arg.ID, arg.ProjectID)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Locator,
		&i.CreatedAt,
	)
	return i, err
}

const getTarget = `-- name: GetTarget :one
SELECT id, project_id, name, kind, locator, created_at FROM targets
WHERE id = $1 AND project_id = $2
LIMIT 1
`

type GetTargetParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetTarget(ctx context.Context, arg GetTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, getTarget, arg.ID, arg.ProjectID)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Locator,
		&i.CreatedAt,
	)
	return i, err
}

const listTargets = `-- name: ListTargets :many
SELECT id, project_id, name, kind, locator, created_at FROM targets
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) ListTargets(ctx context.Context, projectID pgtype.UUID) ([]Target, error) {
	rows, err := q.db.Query(ctx, listTargets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Locator,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTarget = `-- name: UpsertTarget :one
INSERT INTO targets (project_id, name, kind, locator)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, name)
DO UPDATE SET
    kind = EXCLUDED.kind,
    locator = EXCLUDED.locator
RETURNING id, project_id, name, kind, locator, created_at
`

type UpsertTargetParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Kind      string      `json:"kind"`
	Locator   pgtype.Text `json:"locator"`
}

func (q *Queries) UpsertTarget(ctx context.Context, arg UpsertTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, upsertTarget,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Locator,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Locator,
		&i.CreatedAt,
	)
	return i, err
}
