// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateTeamParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Description)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const effectiveProjectRole = `-- name: EffectiveProjectRole :one
SELECT ranked.role FROM (
    SELECT role,
        CASE role WHEN 'admin' THEN 3 WHEN 'editor' THEN 2 ELSE 1 END AS rank
    FROM (
        SELECT pm.role FROM project_members pm WHERE pm.project_id = $1 AND pm.user_id = $2
        UNION ALL
        SELECT pt.role FROM project_teams pt
        JOIN team_members tm ON tm.team_id = pt.team_id
        WHERE pt.project_id = $1 AND tm.user_id = $2
    ) roles
) ranked
ORDER BY ranked.rank DESC
LIMIT 1
`

type EffectiveProjectRoleParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

// The strongest role a user holds on a project across direct membership
// and team links (admin > editor > viewer). pgx.ErrNoRows means no access
// at all — callers treat it as denial, never as a default role.
func (q *Queries) EffectiveProjectRole(ctx context.Context, arg EffectiveProjectRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, effectiveProjectRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, description, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, name, description, created_at, updated_at FROM teams WHERE name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isProjectMemberEffective = `-- name: IsProjectMemberEffective :one
SELECT EXISTS (
    SELECT 1 FROM project_members pm WHERE pm.project_id = $1 AND pm.user_id = $2
) OR EXISTS (
    SELECT 1 FROM project_teams pt
    JOIN team_members tm ON tm.team_id = pt.team_id
    WHERE pt.project_id = $1 AND tm.user_id = $2
) AS is_member
`

type IsProjectMemberEffectiveParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

// Effective membership: a direct project_members row OR membership in any
// team linked to the project. The single choke point for session-user
// project access.
func (q *Queries) IsProjectMemberEffective(ctx context.Context, arg IsProjectMemberEffectiveParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isProjectMemberEffective, arg.ProjectID, arg.UserID)
	var is_member pgtype.Bool
	err := row.Scan(&is_member)
	return is_member, err
}

const isTeamAdmin = `-- name: IsTeamAdmin :one
SELECT EXISTS (
    SELECT 1 FROM team_members WHERE team_id = $1 AND user_id = $2 AND role = 'admin'
) AS is_admin
`

type IsTeamAdminParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsTeamAdmin(ctx context.Context, arg IsTeamAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamAdmin, arg.TeamID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const isTeamMember = `-- name: IsTeamMember :one
SELECT EXISTS (
    SELECT 1 FROM team_members WHERE team_id = $1 AND user_id = $2
) AS is_member
`

type IsTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamMember, arg.TeamID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const linkProjectTeam = `-- name: LinkProjectTeam :one
INSERT INTO project_teams (project_id, team_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, team_id) DO UPDATE SET role = EXCLUDED.role
RETURNING project_id, team_id, role, created_at
`

type LinkProjectTeamParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TeamID    pgtype.UUID `json:"team_id"`
	Role      string      `json:"role"`
}

func (q *Queries) LinkProjectTeam(ctx context.Context, arg LinkProjectTeamParams) (ProjectTeam, error) {
	row := q.db.QueryRow(ctx, linkProjectTeam, arg.ProjectID, arg.TeamID, arg.Role)
	var i ProjectTeam
	err := row.Scan(
		&i.ProjectID,
		&i.TeamID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessibleProjectIDs = `-- name: ListAccessibleProjectIDs :many
SELECT pm.project_id FROM project_members pm WHERE pm.user_id = $1
UNION
SELECT pt.project_id FROM project_teams pt
JOIN team_members tm ON tm.team_id = pt.team_id
WHERE tm.user_id = $1
`

// Every project a user reaches directly or through a team, for the
// batched list path (replaces per-project checks).
func (q *Queries) ListAccessibleProjectIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAccessibleProjectIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var project_id pgtype.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTeams = `-- name: ListProjectTeams :many
SELECT pt.project_id, pt.team_id, pt.role, pt.created_at, t.name AS team_name
FROM project_teams pt
JOIN teams t ON t.id = pt.team_id
WHERE pt.project_id = $1
ORDER BY t.name ASC
`

type ListProjectTeamsRow struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TeamName  string             `json:"team_name"`
}

func (q *Queries) ListProjectTeams(ctx context.Context, projectID pgtype.UUID) ([]ListProjectTeamsRow, error) {
	rows, err := q.db.Query(ctx, listProjectTeams, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectTeamsRow
	for rows.Next() {
		var i ListProjectTeamsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.TeamID,
			&i.Role,
			&i.CreatedAt,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.team_id, tm.user_id, tm.role, tm.created_at, u.email
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY u.email ASC
`

type ListTeamMembersRow struct {
	TeamID    pgtype.UUID        `json:"team_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Email     string             `json:"email"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, description, created_at, updated_at FROM teams
ORDER BY name ASC
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const unlinkProjectTeam = `-- name: UnlinkProjectTeam :exec
DELETE FROM project_teams WHERE project_id = $1 AND team_id = $2
`

type UnlinkProjectTeamParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TeamID    pgtype.UUID `json:"team_id"`
}

func (q *Queries) UnlinkProjectTeam(ctx context.Context, arg UnlinkProjectTeamParams) error {
	_, err := q.db.Exec(ctx, unlinkProjectTeam, arg.ProjectID, arg.TeamID)
	return err
}

const upsertTeamMember = `-- name: UpsertTeamMember :one
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING team_id, user_id, role, created_at
`

type UpsertTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpsertTeamMember(ctx context.Context, arg UpsertTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, upsertTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
