// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waivers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWaiver = `-- name: CreateWaiver :one
INSERT INTO waivers (project_id, name, description, enabled, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, description, enabled, created_at, updated_at, expires_at
`

type CreateWaiverParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Enabled     bool               `json:"enabled"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateWaiver(ctx context.Context, arg CreateWaiverParams) (Waiver, error) {
	row := q.db.QueryRow(ctx, createWaiver,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.ExpiresAt,
	)
	var i Waiver
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createWaiverCondition = `-- name: CreateWaiverCondition :one
INSERT INTO waiver_conditions (waiver_id, field, operator, value)
VALUES ($1, $2, $3, $4)
RETURNING id, waiver_id, field, operator, value, created_at
`

type CreateWaiverConditionParams struct {
	WaiverID pgtype.UUID `json:"waiver_id"`
	Field    string      `json:"field"`
	Operator string      `json:"operator"`
	Value    string      `json:"value"`
}

func (q *Queries) CreateWaiverCondition(ctx context.Context, arg CreateWaiverConditionParams) (WaiverCondition, error) {
	row := q.db.QueryRow(ctx, createWaiverCondition,
		arg.WaiverID,
		arg.Field,
		arg.Operator,
		arg.Value,
	)
	var i WaiverCondition
	err := row.Scan(
		&i.ID,
		&i.WaiverID,
		&i.Field,
		&i.Operator,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const createWaiverContext = `-- name: CreateWaiverContext :one
INSERT INTO waiver_contexts (waiver_id, environment_id, target_id, artifact_id)
VALUES ($1, $2, $3, $4)
RETURNING id, waiver_id, environment_id, target_id, artifact_id, created_at
`

type CreateWaiverContextParams struct {
	WaiverID      pgtype.UUID `json:"waiver_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	TargetID      pgtype.UUID `json:"target_id"`
	ArtifactID    pgtype.UUID `json:"artifact_id"`
}

func (q *Queries) CreateWaiverContext(ctx context.Context, arg CreateWaiverContextParams) (WaiverContext, error) {
	row := q.db.QueryRow(ctx, createWaiverContext,
		arg.WaiverID,
		arg.EnvironmentID,
		arg.TargetID,
		arg.ArtifactID,
	)
	var i WaiverContext
	err := row.Scan(
		&i.ID,
		&i.WaiverID,
		&i.EnvironmentID,
		&i.TargetID,
		&i.ArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const createWaiverEvent = `-- name: CreateWaiverEvent :one
INSERT INTO waiver_events (waiver_id, event_type, actor_id, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, waiver_id, event_type, actor_id, metadata, created_at
`

type CreateWaiverEventParams struct {
	WaiverID  pgtype.UUID `json:"waiver_id"`
	EventType string      `json:"event_type"`
	ActorID   pgtype.Text `json:"actor_id"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateWaiverEvent(ctx context.Context, arg CreateWaiverEventParams) (WaiverEvent, error) {
	row := q.db.QueryRow(ctx, createWaiverEvent,
		arg.WaiverID,
		arg.EventType,
		arg.ActorID,
		arg.Metadata,
	)
	var i WaiverEvent
	err := row.Scan(
		&i.ID,
		&i.WaiverID,
		&i.EventType,
		&i.ActorID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createWaiverFindingTarget = `-- name: CreateWaiverFindingTarget :one
INSERT INTO waiver_finding_targets (waiver_id, finding_id)
VALUES ($1, $2)
RETURNING id, waiver_id, finding_id, created_at
`

type CreateWaiverFindingTargetParams struct {
	WaiverID  pgtype.UUID `json:"waiver_id"`
	FindingID pgtype.UUID `json:"finding_id"`
}

func (q *Queries) CreateWaiverFindingTarget(ctx context.Context, arg CreateWaiverFindingTargetParams) (WaiverFindingTarget, error) {
	row := q.db.QueryRow(ctx, createWaiverFindingTarget, arg.WaiverID, arg.FindingID)
	var i WaiverFindingTarget
	err := row.Scan(
		&i.ID,
		&i.WaiverID,
		&i.FindingID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWaiver = `-- name: DeleteWaiver :one
DELETE FROM waivers
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, description, enabled, created_at, updated_at, expires_at
`

type DeleteWaiverParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteWaiver(ctx context.Context, arg DeleteWaiverParams) (Waiver, error) {
	row := q.db.QueryRow(ctx, deleteWaiver, arg.ID, arg.ProjectID)
	var i Waiver
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteWaiverConditions = `-- name: DeleteWaiverConditions :exec
DELETE FROM waiver_conditions WHERE waiver_id = $1
`

func (q *Queries) DeleteWaiverConditions(ctx context.Context, waiverID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWaiverConditions, waiverID)
	return err
}

const deleteWaiverContexts = `-- name: DeleteWaiverContexts :exec
DELETE FROM waiver_contexts WHERE waiver_id = $1
`

func (q *Queries) DeleteWaiverContexts(ctx context.Context, waiverID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWaiverContexts, waiverID)
	return err
}

const deleteWaiverFindingTargets = `-- name: DeleteWaiverFindingTargets :exec
DELETE FROM waiver_finding_targets WHERE waiver_id = $1
`

func (q *Queries) DeleteWaiverFindingTargets(ctx context.Context, waiverID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWaiverFindingTargets, waiverID)
	return err
}

const getWaiver = `-- name: GetWaiver :one
SELECT id, project_id, name, description, enabled, created_at, updated_at, expires_at FROM waivers
WHERE id = $1 AND project_id = $2
`

type GetWaiverParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) GetWaiver(ctx context.Context, arg GetWaiverParams) (Waiver, error) {
	row := q.db.QueryRow(ctx, getWaiver, arg.ID, arg.ProjectID)
	var i Waiver
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveWaivers = `-- name: ListActiveWaivers :many
SELECT id, project_id, name, description, enabled, created_at, updated_at, expires_at FROM waivers
WHERE project_id = $1
  AND enabled = true
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) ListActiveWaivers(ctx context.Context, projectID pgtype.UUID) ([]Waiver, error) {
	rows, err := q.db.Query(ctx, listActiveWaivers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Waiver
	for rows.Next() {
		var i Waiver
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverConditions = `-- name: ListWaiverConditions :many
SELECT id, waiver_id, field, operator, value, created_at FROM waiver_conditions
WHERE waiver_id = $1
ORDER BY created_at
`

func (q *Queries) ListWaiverConditions(ctx context.Context, waiverID pgtype.UUID) ([]WaiverCondition, error) {
	rows, err := q.db.Query(ctx, listWaiverConditions, waiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverCondition
	for rows.Next() {
		var i WaiverCondition
		if err := rows.Scan(
			&i.ID,
			&i.WaiverID,
			&i.Field,
			&i.Operator,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverConditionsByWaiverIDs = `-- name: ListWaiverConditionsByWaiverIDs :many
SELECT id, waiver_id, field, operator, value, created_at FROM waiver_conditions
WHERE waiver_id = ANY($1::uuid[])
ORDER BY created_at
`

func (q *Queries) ListWaiverConditionsByWaiverIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]WaiverCondition, error) {
	rows, err := q.db.Query(ctx, listWaiverConditionsByWaiverIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverCondition
	for rows.Next() {
		var i WaiverCondition
		if err := rows.Scan(
			&i.ID,
			&i.WaiverID,
			&i.Field,
			&i.Operator,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverContexts = `-- name: ListWaiverContexts :many
SELECT id, waiver_id, environment_id, target_id, artifact_id, created_at FROM waiver_contexts
WHERE waiver_id = $1
ORDER BY created_at
`

func (q *Queries) ListWaiverContexts(ctx context.Context, waiverID pgtype.UUID) ([]WaiverContext, error) {
	rows, err := q.db.Query(ctx, listWaiverContexts, waiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverContext
	for rows.Next() {
		var i WaiverContext
		if err := rows.Scan(
			&i.ID,
			&i.WaiverID,
			&i.EnvironmentID,
			&i.TargetID,
			&i.ArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverContextsByWaiverIDs = `-- name: ListWaiverContextsByWaiverIDs :many
SELECT id, waiver_id, environment_id, target_id, artifact_id, created_at FROM waiver_contexts
WHERE waiver_id = ANY($1::uuid[])
ORDER BY created_at
`

func (q *Queries) ListWaiverContextsByWaiverIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]WaiverContext, error) {
	rows, err := q.db.Query(ctx, listWaiverContextsByWaiverIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverContext
	for rows.Next() {
		var i WaiverContext
		if err := rows.Scan(
			&i.ID,
			&i.WaiverID,
			&i.EnvironmentID,
			&i.TargetID,
			&i.ArtifactID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverEvents = `-- name: ListWaiverEvents :many
SELECT id, waiver_id, event_type, actor_id, metadata, created_at FROM waiver_events
WHERE waiver_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWaiverEvents(ctx context.Context, waiverID pgtype.UUID) ([]WaiverEvent, error) {
	rows, err := q.db.Query(ctx, listWaiverEvents, waiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverEvent
	for rows.Next() {
		var i WaiverEvent
		if err := rows.Scan(
			&i.ID,
			&i.WaiverID,
			&i.EventType,
			&i.ActorID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverFindingTargets = `-- name: ListWaiverFindingTargets :many
SELECT id, waiver_id, finding_id, created_at FROM waiver_finding_targets
WHERE waiver_id = $1
ORDER BY created_at
`

func (q *Queries) ListWaiverFindingTargets(ctx context.Context, waiverID pgtype.UUID) ([]WaiverFindingTarget, error) {
	rows, err := q.db.Query(ctx, listWaiverFindingTargets, waiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverFindingTarget
	for rows.Next() {
		var i WaiverFindingTarget
		if err := rows.Scan(
			&i.ID,
			&i.WaiverID,
			&i.FindingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiverFindingTargetsByWaiverIDs = `-- name: ListWaiverFindingTargetsByWaiverIDs :many
SELECT id, waiver_id, finding_id, created_at FROM waiver_finding_targets
WHERE waiver_id = ANY($1::uuid[])
ORDER BY created_at
`

func (q *Queries) ListWaiverFindingTargetsByWaiverIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]WaiverFindingTarget, error) {
	rows, err := q.db.Query(ctx, listWaiverFindingTargetsByWaiverIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverFindingTarget
	for rows.Next() {
		var i WaiverFindingTarget
		if err := rows.Scan(
			&i.ID,
			&i.WaiverID,
			&i.FindingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaivers = `-- name: ListWaivers :many
SELECT id, project_id, name, description, enabled, created_at, updated_at, expires_at FROM waivers
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWaivers(ctx context.Context, projectID pgtype.UUID) ([]Waiver, error) {
	rows, err := q.db.Query(ctx, listWaivers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Waiver
	for rows.Next() {
		var i Waiver
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleWaiver = `-- name: ToggleWaiver :one
UPDATE waivers SET
    enabled = NOT enabled,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, description, enabled, created_at, updated_at, expires_at
`

type ToggleWaiverParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) ToggleWaiver(ctx context.Context, arg ToggleWaiverParams) (Waiver, error) {
	row := q.db.QueryRow(ctx, toggleWaiver, arg.ID, arg.ProjectID)
	var i Waiver
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateWaiver = `-- name: UpdateWaiver :one
UPDATE waivers SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    expires_at = CASE WHEN $5::boolean
        THEN $6::timestamptz ELSE expires_at END,
    updated_at = NOW()
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, name, description, enabled, created_at, updated_at, expires_at
`

type UpdateWaiverParams struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	SetExpires  bool               `json:"set_expires"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// set_expires selects whether expires_at is written: true binds the new
// value (NULL clears it), false leaves the stored expiry untouched.
func (q *Queries) UpdateWaiver(ctx context.Context, arg UpdateWaiverParams) (Waiver, error) {
	row := q.db.QueryRow(ctx, updateWaiver,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.SetExpires,
		arg.ExpiresAt,
	)
	var i Waiver
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
