// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waiver_expiry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireWaivers = `-- name: ExpireWaivers :many
UPDATE waivers SET
    enabled = false,
    updated_at = NOW()
WHERE enabled = true AND expires_at IS NOT NULL AND expires_at <= NOW()
RETURNING id, project_id, name
`

type ExpireWaiversRow struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) ExpireWaivers(ctx context.Context) ([]ExpireWaiversRow, error) {
	rows, err := q.db.Query(ctx, expireWaivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireWaiversRow
	for rows.Next() {
		var i ExpireWaiversRow
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
