// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watcher.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWatcherState = `-- name: GetWatcherState :one
SELECT id, last_successful_poll_at
FROM watcher_state
WHERE id = 1
`

// The single-row watcher_state table (migration 000017; id = 1 enforced by
// CHECK). Returns pgx.ErrNoRows when no poll has ever completed — the
// daemon treats that as the cold-start condition.
func (q *Queries) GetWatcherState(ctx context.Context) (WatcherState, error) {
	row := q.db.QueryRow(ctx, getWatcherState)
	var i WatcherState
	err := row.Scan(&i.ID, &i.LastSuccessfulPollAt)
	return i, err
}

const updateWatcherState = `-- name: UpdateWatcherState :exec
INSERT INTO watcher_state (id, last_successful_poll_at)
VALUES (1, $1::timestamptz)
ON CONFLICT (id) DO UPDATE SET
    last_successful_poll_at = EXCLUDED.last_successful_poll_at
`

// Advances the poll watermark. The row is created on the first success (the
// default id 1 satisfies the CHECK constraint) and updated thereafter. The
// watermark advances only after a fully successful poll.
func (q *Queries) UpdateWatcherState(ctx context.Context, dollar_1 pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, updateWatcherState, dollar_1)
	return err
}
