apiVersion: v1
kind: Secret
metadata:
  name: {{- include "specht.fullname" . | quote -}}
  labels:
    app.kubernetes.io/name: {{- include "specht.name" . | quote -}}
    app.kubernetes.io/instance: {{.Release.Name | quote}}
type: Opaque
stringData:
  # The postgresql subchart's service is named <release>-postgresql.
  database-url: >-
    postgres://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@
    {{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.database }}?sslmode={{ .Values.postgresql.sslmode | default "require" }}
